run:
  timeout: 10m
  go: '1.25'
  allow-parallel-runners: true

linters:
  enable:
    # Error detection & correctness
    - errcheck        # Check for unchecked errors
    - govet           # Go vet examines Go source code
    - staticcheck     # Comprehensive static analysis
    - ineffassign     # Detect ineffectual assignments
    - unused          # Check for unused code
    - gosimple        # Simplify code
    - bodyclose       # Ensure HTTP response body is closed
    - errchkjson      # Check for unchecked errors in JSON marshaling
    - nilerr          # Detect returning nil when error should be returned
    - nilnil          # Detect returning nil when nil should be returned

    # Security
    - gosec           # Security problems

    # Style & best practices
    - revive          # Replacement for golint
    - gocritic        # Opinionated Go source code linter
    - gofmt           # Check if code is formatted with gofmt
    - goimports       # Check if imports are formatted
    - misspell        # Detect commonly misspelled words
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Detect unused function parameters
    - nakedret        # Detect naked returns in functions > 30 lines
    - whitespace      # Detect leading/trailing whitespace
    - godot           # Check if comments end in a period
    - importas        # Enforce import aliases
    - goprintffuncname # Check that printf-like functions are named correctly

    # Code complexity
    - gocyclo         # Detect cyclomatic complexity
    - goconst         # Detect repeated strings that should be constants
    - dupl            # Detect code cloning

    # Performance
    - prealloc        # Detect slice declarations that could be preallocated
    - copyloopvar     # Detect loop variable reference issues (Go 1.22+)

    # Maintenance
    - godox           # Detect TODO/FIXME/BUG comments
    - asciicheck      # Ensure only ASCII characters
    - bidichk         # Detect dangerous Unicode bidirectional characters
    - dogsled         # Detect too many blank identifiers
    - makezero        # Detect improper slice/map initialization
    - nolintlint      # Reports ill-formed or insufficient nolint directives

    # Testing
    - thelper         # Detect test helpers without t.Helper() call

linters-settings:
  gocyclo:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  dupl:
    threshold: 500

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - dupImport # False positives with different package versions
      - ifElseChain # Can make code harder to read sometimes
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  govet:
    enable-all: true
    disable:
      - fieldalignment # Too noisy for this project
      - shadow # Sometimes shadowing is intentional

  revive:
    enable-default-rules: true
    rules:
      # Disable some noisy rules
      - name: exported
        disabled: true # Too noisy for internal packages
      - name: package-comments
        disabled: true # Not all packages need comments
      - name: var-naming
        disabled: false
        arguments:
          - ["ID"] # Allow ID instead of Id
      - name: function-length
        disabled: false
        arguments: [50, 0] # Warn on functions > 50 lines
      - name: cognitive-complexity
        disabled: false
        arguments: [20]
      - name: cyclomatic
        disabled: false
        arguments: [20]

  importas:
    no-unaliased: true
    alias:
      # Kubernetes core
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: k8s.io/client-go/kubernetes/typed/core/v1
        alias: corev1client
      # HAProxy client
      - pkg: github.com/haproxytech/client-native/v6
        alias: haproxy

  gosec:
    excludes:
      - G114 # Use of net/http serve functions without timeouts - handled at infrastructure level
      - G404 # Use of weak random - not used for security purposes

  godox:
    keywords:
      - BUG
      - FIXME
      - HACK

  nakedret:
    max-func-lines: 30

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

  exclude-rules:
    # Exclude generated code
    - path: codegen/.*\.gen\.go$
      linters:
        - all

    # Exclude zz_generated files (if any in future)
    - path: zz_generated\..*\.go$
      linters:
        - all

    # Relax rules for test files
    - path: _test\.go$
      linters:
        - errcheck
        - dupl
        - gosec
        - goconst
        - gocyclo
        - funlen

    # Disable dupl for section operation files - intentional structural similarity for type-specific wrappers
    - path: pkg/dataplane/comparator/sections/
      linters:
        - dupl
    - path: pkg/dataplane/auxiliaryfiles/
      linters:
        - dupl

    # Relax rules for integration test helpers
    - path: tests/integration/
      linters:
        - errcheck
        - gosec
        - goconst
        - gocyclo

    # Allow dot imports in test files (for gomega/ginkgo if used)
    - path: _test\.go$
      text: "should not use dot imports"

    # Allow long lines in generated files
    - path: codegen/
      linters:
        - lll

    # Ignore certain patterns
    - text: "G304: Potential file inclusion via variable"
      linters:
        - gosec
      path: tests/integration/

    # Allow TODO comments in example code
    - path: examples/
      linters:
        - godox

  exclude-dirs:
    - vendor
    - third_party
    - charts # Helm charts directory

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
