# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  - repo: local
    hooks:
      # Run linting (golangci-lint + arch-go + eventimmutability)
      - id: make-lint
        name: make lint
        entry: make lint
        language: system
        pass_filenames: false
        files: \.go$

      # Run security audit (govulncheck)
      - id: make-audit
        name: make audit
        entry: make audit
        language: system
        pass_filenames: false
        always_run: true
