//go:build !ignore_autogenerated

// Copyright 2025 Philipp Hossner
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuxiliaryFileReferences) DeepCopyInto(out *AuxiliaryFileReferences) {
	*out = *in
	if in.MapFiles != nil {
		in, out := &in.MapFiles, &out.MapFiles
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.SSLCertificates != nil {
		in, out := &in.SSLCertificates, &out.SSLCertificates
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuxiliaryFileReferences.
func (in *AuxiliaryFileReferences) DeepCopy() *AuxiliaryFileReferences {
	if in == nil {
		return nil
	}
	out := new(AuxiliaryFileReferences)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMetadata) DeepCopyInto(out *ConfigMetadata) {
	*out = *in
	if in.RenderedAt != nil {
		in, out := &in.RenderedAt, &out.RenderedAt
		*out = (*in).DeepCopy()
	}
	if in.ValidatedAt != nil {
		in, out := &in.ValidatedAt, &out.ValidatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMetadata.
func (in *ConfigMetadata) DeepCopy() *ConfigMetadata {
	if in == nil {
		return nil
	}
	out := new(ConfigMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfig) DeepCopyInto(out *ControllerConfig) {
	*out = *in
	in.LeaderElection.DeepCopyInto(&out.LeaderElection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfig.
func (in *ControllerConfig) DeepCopy() *ControllerConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataplaneConfig) DeepCopyInto(out *DataplaneConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataplaneConfig.
func (in *DataplaneConfig) DeepCopy() *DataplaneConfig {
	if in == nil {
		return nil
	}
	out := new(DataplaneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralFile) DeepCopyInto(out *GeneralFile) {
	*out = *in
	if in.PostProcessing != nil {
		in, out := &in.PostProcessing, &out.PostProcessing
		*out = make([]PostProcessorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralFile.
func (in *GeneralFile) DeepCopy() *GeneralFile {
	if in == nil {
		return nil
	}
	out := new(GeneralFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCfg) DeepCopyInto(out *HAProxyCfg) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCfg.
func (in *HAProxyCfg) DeepCopy() *HAProxyCfg {
	if in == nil {
		return nil
	}
	out := new(HAProxyCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyCfg) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCfgList) DeepCopyInto(out *HAProxyCfgList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HAProxyCfg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCfgList.
func (in *HAProxyCfgList) DeepCopy() *HAProxyCfgList {
	if in == nil {
		return nil
	}
	out := new(HAProxyCfgList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyCfgList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCfgSpec) DeepCopyInto(out *HAProxyCfgSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCfgSpec.
func (in *HAProxyCfgSpec) DeepCopy() *HAProxyCfgSpec {
	if in == nil {
		return nil
	}
	out := new(HAProxyCfgSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyCfgStatus) DeepCopyInto(out *HAProxyCfgStatus) {
	*out = *in
	if in.DeployedToPods != nil {
		in, out := &in.DeployedToPods, &out.DeployedToPods
		*out = make([]PodDeploymentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuxiliaryFiles != nil {
		in, out := &in.AuxiliaryFiles, &out.AuxiliaryFiles
		*out = new(AuxiliaryFileReferences)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(ConfigMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyCfgStatus.
func (in *HAProxyCfgStatus) DeepCopy() *HAProxyCfgStatus {
	if in == nil {
		return nil
	}
	out := new(HAProxyCfgStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyConfig) DeepCopyInto(out *HAProxyConfig) {
	*out = *in
	if in.PostProcessing != nil {
		in, out := &in.PostProcessing, &out.PostProcessing
		*out = make([]PostProcessorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyConfig.
func (in *HAProxyConfig) DeepCopy() *HAProxyConfig {
	if in == nil {
		return nil
	}
	out := new(HAProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyMapFile) DeepCopyInto(out *HAProxyMapFile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyMapFile.
func (in *HAProxyMapFile) DeepCopy() *HAProxyMapFile {
	if in == nil {
		return nil
	}
	out := new(HAProxyMapFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyMapFile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyMapFileList) DeepCopyInto(out *HAProxyMapFileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HAProxyMapFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyMapFileList.
func (in *HAProxyMapFileList) DeepCopy() *HAProxyMapFileList {
	if in == nil {
		return nil
	}
	out := new(HAProxyMapFileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyMapFileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyMapFileSpec) DeepCopyInto(out *HAProxyMapFileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyMapFileSpec.
func (in *HAProxyMapFileSpec) DeepCopy() *HAProxyMapFileSpec {
	if in == nil {
		return nil
	}
	out := new(HAProxyMapFileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyMapFileStatus) DeepCopyInto(out *HAProxyMapFileStatus) {
	*out = *in
	if in.DeployedToPods != nil {
		in, out := &in.DeployedToPods, &out.DeployedToPods
		*out = make([]PodDeploymentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyMapFileStatus.
func (in *HAProxyMapFileStatus) DeepCopy() *HAProxyMapFileStatus {
	if in == nil {
		return nil
	}
	out := new(HAProxyMapFileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateConfig) DeepCopyInto(out *HAProxyTemplateConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateConfig.
func (in *HAProxyTemplateConfig) DeepCopy() *HAProxyTemplateConfig {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyTemplateConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateConfigList) DeepCopyInto(out *HAProxyTemplateConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HAProxyTemplateConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateConfigList.
func (in *HAProxyTemplateConfigList) DeepCopy() *HAProxyTemplateConfigList {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HAProxyTemplateConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateConfigSpec) DeepCopyInto(out *HAProxyTemplateConfigSpec) {
	*out = *in
	out.CredentialsSecretRef = in.CredentialsSecretRef
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	in.Controller.DeepCopyInto(&out.Controller)
	out.Logging = in.Logging
	out.Dataplane = in.Dataplane
	in.TemplatingSettings.DeepCopyInto(&out.TemplatingSettings)
	if in.WatchedResourcesIgnoreFields != nil {
		in, out := &in.WatchedResourcesIgnoreFields, &out.WatchedResourcesIgnoreFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WatchedResources != nil {
		in, out := &in.WatchedResources, &out.WatchedResources
		*out = make(map[string]WatchedResource, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.TemplateSnippets != nil {
		in, out := &in.TemplateSnippets, &out.TemplateSnippets
		*out = make(map[string]TemplateSnippet, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Maps != nil {
		in, out := &in.Maps, &out.Maps
		*out = make(map[string]MapFile, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make(map[string]GeneralFile, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.SSLCertificates != nil {
		in, out := &in.SSLCertificates, &out.SSLCertificates
		*out = make(map[string]SSLCertificate, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.HAProxyConfig.DeepCopyInto(&out.HAProxyConfig)
	if in.ValidationTests != nil {
		in, out := &in.ValidationTests, &out.ValidationTests
		*out = make(map[string]ValidationTest, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateConfigSpec.
func (in *HAProxyTemplateConfigSpec) DeepCopy() *HAProxyTemplateConfigSpec {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAProxyTemplateConfigStatus) DeepCopyInto(out *HAProxyTemplateConfigStatus) {
	*out = *in
	if in.LastValidated != nil {
		in, out := &in.LastValidated, &out.LastValidated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAProxyTemplateConfigStatus.
func (in *HAProxyTemplateConfigStatus) DeepCopy() *HAProxyTemplateConfigStatus {
	if in == nil {
		return nil
	}
	out := new(HAProxyTemplateConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPResourceFixture) DeepCopyInto(out *HTTPResourceFixture) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPResourceFixture.
func (in *HTTPResourceFixture) DeepCopy() *HTTPResourceFixture {
	if in == nil {
		return nil
	}
	out := new(HTTPResourceFixture)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeaderElectionConfig) DeepCopyInto(out *LeaderElectionConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderElectionConfig.
func (in *LeaderElectionConfig) DeepCopy() *LeaderElectionConfig {
	if in == nil {
		return nil
	}
	out := new(LeaderElectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapFile) DeepCopyInto(out *MapFile) {
	*out = *in
	if in.PostProcessing != nil {
		in, out := &in.PostProcessing, &out.PostProcessing
		*out = make([]PostProcessorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapFile.
func (in *MapFile) DeepCopy() *MapFile {
	if in == nil {
		return nil
	}
	out := new(MapFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationSummary) DeepCopyInto(out *OperationSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationSummary.
func (in *OperationSummary) DeepCopy() *OperationSummary {
	if in == nil {
		return nil
	}
	out := new(OperationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDeploymentStatus) DeepCopyInto(out *PodDeploymentStatus) {
	*out = *in
	in.DeployedAt.DeepCopyInto(&out.DeployedAt)
	if in.LastCheckedAt != nil {
		in, out := &in.LastCheckedAt, &out.LastCheckedAt
		*out = (*in).DeepCopy()
	}
	if in.LastReloadAt != nil {
		in, out := &in.LastReloadAt, &out.LastReloadAt
		*out = (*in).DeepCopy()
	}
	if in.SyncDuration != nil {
		in, out := &in.SyncDuration, &out.SyncDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.LastOperationSummary != nil {
		in, out := &in.LastOperationSummary, &out.LastOperationSummary
		*out = new(OperationSummary)
		**out = **in
	}
	if in.LastErrorAt != nil {
		in, out := &in.LastErrorAt, &out.LastErrorAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDeploymentStatus.
func (in *PodDeploymentStatus) DeepCopy() *PodDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(PodDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSelector) DeepCopyInto(out *PodSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSelector.
func (in *PodSelector) DeepCopy() *PodSelector {
	if in == nil {
		return nil
	}
	out := new(PodSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostProcessorConfig) DeepCopyInto(out *PostProcessorConfig) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostProcessorConfig.
func (in *PostProcessorConfig) DeepCopy() *PostProcessorConfig {
	if in == nil {
		return nil
	}
	out := new(PostProcessorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLCertificate) DeepCopyInto(out *SSLCertificate) {
	*out = *in
	if in.PostProcessing != nil {
		in, out := &in.PostProcessing, &out.PostProcessing
		*out = make([]PostProcessorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLCertificate.
func (in *SSLCertificate) DeepCopy() *SSLCertificate {
	if in == nil {
		return nil
	}
	out := new(SSLCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateSnippet) DeepCopyInto(out *TemplateSnippet) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateSnippet.
func (in *TemplateSnippet) DeepCopy() *TemplateSnippet {
	if in == nil {
		return nil
	}
	out := new(TemplateSnippet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplatingSettings) DeepCopyInto(out *TemplatingSettings) {
	*out = *in
	in.ExtraContext.DeepCopyInto(&out.ExtraContext)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplatingSettings.
func (in *TemplatingSettings) DeepCopy() *TemplatingSettings {
	if in == nil {
		return nil
	}
	out := new(TemplatingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationAssertion) DeepCopyInto(out *ValidationAssertion) {
	*out = *in
	if in.Patterns != nil {
		in, out := &in.Patterns, &out.Patterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationAssertion.
func (in *ValidationAssertion) DeepCopy() *ValidationAssertion {
	if in == nil {
		return nil
	}
	out := new(ValidationAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationTest) DeepCopyInto(out *ValidationTest) {
	*out = *in
	if in.Fixtures != nil {
		in, out := &in.Fixtures, &out.Fixtures
		*out = make(map[string][]runtime.RawExtension, len(*in))
		for key, val := range *in {
			var outVal []runtime.RawExtension
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]runtime.RawExtension, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.HTTPResources != nil {
		in, out := &in.HTTPResources, &out.HTTPResources
		*out = make([]HTTPResourceFixture, len(*in))
		copy(*out, *in)
	}
	if in.Assertions != nil {
		in, out := &in.Assertions, &out.Assertions
		*out = make([]ValidationAssertion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationTest.
func (in *ValidationTest) DeepCopy() *ValidationTest {
	if in == nil {
		return nil
	}
	out := new(ValidationTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchedResource) DeepCopyInto(out *WatchedResource) {
	*out = *in
	if in.IndexBy != nil {
		in, out := &in.IndexBy, &out.IndexBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchedResource.
func (in *WatchedResource) DeepCopy() *WatchedResource {
	if in == nil {
		return nil
	}
	out := new(WatchedResource)
	in.DeepCopyInto(out)
	return out
}
