apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: haproxy-template-ic
resources:
- ../../base

images:
- name: ghcr.io/phihos/haproxy-template-ingress-controller
  newName: haproxy-template-ic
  newTag: dev
- name: haproxytech/haproxy-alpine
  newName: haproxytech/haproxy-alpine
  newTag: "3.1"


patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: haproxy-template-ic-config
  target:
    kind: Deployment
    name: haproxy-template-ic
- path: service-patch.yaml
- path: networkpolicy-patch.yaml
- path: service-controller-patch.yaml
