apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.controller.configmapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haproxy-template-ic-go.labels" . | nindent 4 }}
data:
  config: |
    {{ .Values.controller.config | toYaml | nindent 4 }}
