apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy-template-ic-go.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haproxy-template-ic-go.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.healthzPort }}
      targetPort: healthz
      protocol: TCP
      name: healthz
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "haproxy-template-ic-go.selectorLabels" . | nindent 4 }}
