apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-template-ic
  namespace: haproxy-template-ic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-template-ic
  template:
    metadata:
      labels:
        app: haproxy-template-ic
    spec:
      serviceAccountName: haproxy-template-ic
      containers:
        - name: controller
          image: ghcr.io/phihos/haproxy-template-ingress-controller:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIGMAP_NAME
              value: haproxy-template-ic-config
            - name: VERBOSE
              value: "2"
            - name: HEALTHZ_PORT
              value: "8080"
            - name: SOCKET_PATH
              value: /run/haproxy-template-ic/management.sock
            - name: METRICS_PORT
              value: "9090"
            - name: STRUCTURED_LOGGING
              value: "false"
            - name: TRACING_ENABLED
              value: "false"
          ports:
            - name: healthz
              containerPort: 8080
            - name: metrics
              containerPort: 9090
          volumeMounts:
            - name: run
              mountPath: /run/haproxy-template-ic
      volumes:
        - name: run
          emptyDir: {}
