apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: haproxy-template-ic
  namespace: haproxy-template-ic
  labels:
    app: haproxy-template-ic
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: haproxy-template-ic
