apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: haproxy-template-ic-prod

namePrefix: prod-

resources:
  - ../../base

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
      name: haproxy-template-ic

images:
  - name: ghcr.io/phihos/haproxy-template-ingress-controller
    newTag: stable

replicas:
  - name: haproxy-template-ic
    count: 3
