# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from haproxy_dataplane_v3.models.aws_filters import AwsFilters
from typing import Optional, Set
from typing_extensions import Self

class AwsRegion(BaseModel):
    """
    AWS region configuration
    """ # noqa: E501
    access_key_id: Optional[StrictStr] = Field(default=None, description="AWS Access Key ID.")
    allowlist: Optional[List[AwsFilters]] = Field(default=None, description="Specify the AWS filters used to filter the EC2 instances to add")
    denylist: Optional[List[AwsFilters]] = Field(default=None, description="Specify the AWS filters used to filter the EC2 instances to ignore")
    description: Optional[StrictStr] = None
    enabled: StrictBool
    id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Auto generated ID.")
    ipv4_address: StrictStr = Field(description="Select which IPv4 address the Service Discovery has to use for the backend server entry")
    name: StrictStr
    region: StrictStr
    retry_timeout: Annotated[int, Field(strict=True, ge=1)] = Field(description="Duration in seconds in-between data pulling requests to the AWS region")
    secret_access_key: Optional[StrictStr] = Field(default=None, description="AWS Secret Access Key.")
    server_slots_base: Optional[StrictInt] = None
    server_slots_growth_increment: Optional[StrictInt] = None
    server_slots_growth_type: Optional[StrictStr] = 'exponential'
    __properties: ClassVar[List[str]] = ["access_key_id", "allowlist", "denylist", "description", "enabled", "id", "ipv4_address", "name", "region", "retry_timeout", "secret_access_key", "server_slots_base", "server_slots_growth_increment", "server_slots_growth_type"]

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('ipv4_address')
    def ipv4_address_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['private', 'public']):
            raise ValueError("must be one of enum values ('private', 'public')")
        return value

    @field_validator('server_slots_growth_type')
    def server_slots_growth_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['linear', 'exponential']):
            raise ValueError("must be one of enum values ('linear', 'exponential')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AwsRegion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in allowlist (list)
        _items = []
        if self.allowlist:
            for _item_allowlist in self.allowlist:
                if _item_allowlist:
                    _items.append(_item_allowlist.to_dict())
            _dict['allowlist'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in denylist (list)
        _items = []
        if self.denylist:
            for _item_denylist in self.denylist:
                if _item_denylist:
                    _items.append(_item_denylist.to_dict())
            _dict['denylist'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AwsRegion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access_key_id": obj.get("access_key_id"),
            "allowlist": [AwsFilters.from_dict(_item) for _item in obj["allowlist"]] if obj.get("allowlist") is not None else None,
            "denylist": [AwsFilters.from_dict(_item) for _item in obj["denylist"]] if obj.get("denylist") is not None else None,
            "description": obj.get("description"),
            "enabled": obj.get("enabled"),
            "id": obj.get("id"),
            "ipv4_address": obj.get("ipv4_address"),
            "name": obj.get("name"),
            "region": obj.get("region"),
            "retry_timeout": obj.get("retry_timeout"),
            "secret_access_key": obj.get("secret_access_key"),
            "server_slots_base": obj.get("server_slots_base"),
            "server_slots_growth_increment": obj.get("server_slots_growth_increment"),
            "server_slots_growth_type": obj.get("server_slots_growth_type") if obj.get("server_slots_growth_type") is not None else 'exponential'
        })
        return _obj


