# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class BindParams(BaseModel):
    """
    BindParams
    """ # noqa: E501
    accept_netscaler_cip: Optional[StrictInt] = None
    accept_proxy: Optional[StrictBool] = None
    allow_0rtt: Optional[StrictBool] = None
    alpn: Optional[Annotated[str, Field(strict=True)]] = None
    backlog: Optional[StrictStr] = None
    ca_ignore_err: Optional[StrictStr] = None
    ca_sign_file: Optional[StrictStr] = None
    ca_sign_pass: Optional[StrictStr] = None
    ca_verify_file: Optional[StrictStr] = None
    ciphers: Optional[StrictStr] = None
    ciphersuites: Optional[StrictStr] = None
    client_sigalgs: Optional[StrictStr] = None
    crl_file: Optional[StrictStr] = None
    crt_ignore_err: Optional[StrictStr] = None
    crt_list: Optional[StrictStr] = None
    curves: Optional[StrictStr] = None
    default_crt_list: Optional[List[Annotated[str, Field(strict=True)]]] = None
    defer_accept: Optional[StrictBool] = None
    ecdhe: Optional[StrictStr] = None
    expose_fd_listeners: Optional[StrictBool] = None
    force_sslv3: Optional[StrictBool] = Field(default=None, description="This field is deprecated in favor of sslv3, and will be removed in a future release")
    force_strict_sni: Optional[StrictStr] = None
    force_tlsv10: Optional[StrictBool] = Field(default=None, description="This field is deprecated in favor of tlsv10, and will be removed in a future release")
    force_tlsv11: Optional[StrictBool] = Field(default=None, description="This field is deprecated in favor of tlsv11, and will be removed in a future release")
    force_tlsv12: Optional[StrictBool] = Field(default=None, description="This field is deprecated in favor of tlsv12, and will be removed in a future release")
    force_tlsv13: Optional[StrictBool] = Field(default=None, description="This field is deprecated in favor of tlsv13, and will be removed in a future release")
    generate_certificates: Optional[StrictBool] = None
    gid: Optional[StrictInt] = None
    group: Optional[StrictStr] = None
    guid_prefix: Optional[Annotated[str, Field(strict=True)]] = None
    id: Optional[StrictStr] = None
    idle_ping: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    interface: Optional[StrictStr] = None
    level: Optional[StrictStr] = None
    maxconn: Optional[StrictInt] = None
    mode: Optional[StrictStr] = None
    mss: Optional[StrictStr] = None
    name: Optional[Annotated[str, Field(strict=True)]] = None
    namespace: Optional[StrictStr] = None
    nbconn: Optional[StrictInt] = None
    nice: Optional[StrictInt] = None
    no_alpn: Optional[StrictBool] = None
    no_ca_names: Optional[StrictBool] = None
    no_sslv3: Optional[StrictBool] = Field(default=None, description="This field is deprecated in favor of sslv3, and will be removed in a future release")
    no_strict_sni: Optional[StrictBool] = None
    no_tls_tickets: Optional[StrictBool] = Field(default=None, description="This field is deprecated in favor of tls_tickets, and will be removed in a future release")
    no_tlsv10: Optional[StrictBool] = Field(default=None, description="This field is deprecated in favor of tlsv10, and will be removed in a future release")
    no_tlsv11: Optional[StrictBool] = Field(default=None, description="This field is deprecated in favor of tlsv11, and will be removed in a future release")
    no_tlsv12: Optional[StrictBool] = Field(default=None, description="This field is deprecated in favor of tlsv12, and will be removed in a future release")
    no_tlsv13: Optional[StrictBool] = Field(default=None, description="This field is deprecated in favor of tlsv13, and will be removed in a future release")
    npn: Optional[StrictStr] = None
    prefer_client_ciphers: Optional[StrictBool] = None
    proto: Optional[StrictStr] = None
    quic_cc_algo: Optional[StrictStr] = Field(default=None, alias="quic-cc-algo")
    quic_force_retry: Optional[StrictBool] = Field(default=None, alias="quic-force-retry")
    quic_socket: Optional[StrictStr] = Field(default=None, alias="quic-socket")
    quic_cc_algo_burst_size: Optional[Annotated[int, Field(le=1024, strict=True, ge=0)]] = None
    quic_cc_algo_max_window: Optional[Annotated[int, Field(le=4194304, strict=True, ge=10)]] = None
    severity_output: Optional[StrictStr] = None
    sigalgs: Optional[StrictStr] = None
    ssl: Optional[StrictBool] = None
    ssl_cafile: Optional[Annotated[str, Field(strict=True)]] = None
    ssl_certificate: Optional[Annotated[str, Field(strict=True)]] = None
    ssl_max_ver: Optional[StrictStr] = None
    ssl_min_ver: Optional[StrictStr] = None
    sslv3: Optional[StrictStr] = None
    strict_sni: Optional[StrictBool] = None
    tcp_user_timeout: Optional[StrictInt] = None
    tfo: Optional[StrictBool] = None
    thread: Optional[StrictStr] = None
    tls_ticket_keys: Optional[StrictStr] = None
    tls_tickets: Optional[StrictStr] = None
    tlsv10: Optional[StrictStr] = None
    tlsv11: Optional[StrictStr] = None
    tlsv12: Optional[StrictStr] = None
    tlsv13: Optional[StrictStr] = None
    transparent: Optional[StrictBool] = None
    uid: Optional[StrictStr] = None
    user: Optional[StrictStr] = None
    v4v6: Optional[StrictBool] = None
    v6only: Optional[StrictBool] = None
    verify: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["accept_netscaler_cip", "accept_proxy", "allow_0rtt", "alpn", "backlog", "ca_ignore_err", "ca_sign_file", "ca_sign_pass", "ca_verify_file", "ciphers", "ciphersuites", "client_sigalgs", "crl_file", "crt_ignore_err", "crt_list", "curves", "default_crt_list", "defer_accept", "ecdhe", "expose_fd_listeners", "force_sslv3", "force_strict_sni", "force_tlsv10", "force_tlsv11", "force_tlsv12", "force_tlsv13", "generate_certificates", "gid", "group", "guid_prefix", "id", "idle_ping", "interface", "level", "maxconn", "mode", "mss", "name", "namespace", "nbconn", "nice", "no_alpn", "no_ca_names", "no_sslv3", "no_strict_sni", "no_tls_tickets", "no_tlsv10", "no_tlsv11", "no_tlsv12", "no_tlsv13", "npn", "prefer_client_ciphers", "proto", "quic-cc-algo", "quic-force-retry", "quic-socket", "quic_cc_algo_burst_size", "quic_cc_algo_max_window", "severity_output", "sigalgs", "ssl", "ssl_cafile", "ssl_certificate", "ssl_max_ver", "ssl_min_ver", "sslv3", "strict_sni", "tcp_user_timeout", "tfo", "thread", "tls_ticket_keys", "tls_tickets", "tlsv10", "tlsv11", "tlsv12", "tlsv13", "transparent", "uid", "user", "v4v6", "v6only", "verify"]

    @field_validator('alpn')
    def alpn_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('force_strict_sni')
    def force_strict_sni_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    @field_validator('guid_prefix')
    def guid_prefix_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Za-z0-9-_.:]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9-_.:]+$/")
        return value

    @field_validator('level')
    def level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['user', 'operator', 'admin']):
            raise ValueError("must be one of enum values ('user', 'operator', 'admin')")
        return value

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('quic_cc_algo')
    def quic_cc_algo_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['cubic', 'newreno', 'bbr', 'nocc']):
            raise ValueError("must be one of enum values ('cubic', 'newreno', 'bbr', 'nocc')")
        return value

    @field_validator('quic_socket')
    def quic_socket_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['connection', 'listener']):
            raise ValueError("must be one of enum values ('connection', 'listener')")
        return value

    @field_validator('severity_output')
    def severity_output_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'number', 'string']):
            raise ValueError("must be one of enum values ('none', 'number', 'string')")
        return value

    @field_validator('ssl_cafile')
    def ssl_cafile_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('ssl_certificate')
    def ssl_certificate_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('ssl_max_ver')
    def ssl_max_ver_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SSLv3', 'TLSv1.0', 'TLSv1.1', 'TLSv1.2', 'TLSv1.3']):
            raise ValueError("must be one of enum values ('SSLv3', 'TLSv1.0', 'TLSv1.1', 'TLSv1.2', 'TLSv1.3')")
        return value

    @field_validator('ssl_min_ver')
    def ssl_min_ver_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SSLv3', 'TLSv1.0', 'TLSv1.1', 'TLSv1.2', 'TLSv1.3']):
            raise ValueError("must be one of enum values ('SSLv3', 'TLSv1.0', 'TLSv1.1', 'TLSv1.2', 'TLSv1.3')")
        return value

    @field_validator('sslv3')
    def sslv3_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    @field_validator('tls_tickets')
    def tls_tickets_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    @field_validator('tlsv10')
    def tlsv10_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    @field_validator('tlsv11')
    def tlsv11_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    @field_validator('tlsv12')
    def tlsv12_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    @field_validator('tlsv13')
    def tlsv13_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    @field_validator('verify')
    def verify_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'optional', 'required']):
            raise ValueError("must be one of enum values ('none', 'optional', 'required')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BindParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if idle_ping (nullable) is None
        # and model_fields_set contains the field
        if self.idle_ping is None and "idle_ping" in self.model_fields_set:
            _dict['idle_ping'] = None

        # set to None if quic_cc_algo_burst_size (nullable) is None
        # and model_fields_set contains the field
        if self.quic_cc_algo_burst_size is None and "quic_cc_algo_burst_size" in self.model_fields_set:
            _dict['quic_cc_algo_burst_size'] = None

        # set to None if quic_cc_algo_max_window (nullable) is None
        # and model_fields_set contains the field
        if self.quic_cc_algo_max_window is None and "quic_cc_algo_max_window" in self.model_fields_set:
            _dict['quic_cc_algo_max_window'] = None

        # set to None if tcp_user_timeout (nullable) is None
        # and model_fields_set contains the field
        if self.tcp_user_timeout is None and "tcp_user_timeout" in self.model_fields_set:
            _dict['tcp_user_timeout'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BindParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accept_netscaler_cip": obj.get("accept_netscaler_cip"),
            "accept_proxy": obj.get("accept_proxy"),
            "allow_0rtt": obj.get("allow_0rtt"),
            "alpn": obj.get("alpn"),
            "backlog": obj.get("backlog"),
            "ca_ignore_err": obj.get("ca_ignore_err"),
            "ca_sign_file": obj.get("ca_sign_file"),
            "ca_sign_pass": obj.get("ca_sign_pass"),
            "ca_verify_file": obj.get("ca_verify_file"),
            "ciphers": obj.get("ciphers"),
            "ciphersuites": obj.get("ciphersuites"),
            "client_sigalgs": obj.get("client_sigalgs"),
            "crl_file": obj.get("crl_file"),
            "crt_ignore_err": obj.get("crt_ignore_err"),
            "crt_list": obj.get("crt_list"),
            "curves": obj.get("curves"),
            "default_crt_list": obj.get("default_crt_list"),
            "defer_accept": obj.get("defer_accept"),
            "ecdhe": obj.get("ecdhe"),
            "expose_fd_listeners": obj.get("expose_fd_listeners"),
            "force_sslv3": obj.get("force_sslv3"),
            "force_strict_sni": obj.get("force_strict_sni"),
            "force_tlsv10": obj.get("force_tlsv10"),
            "force_tlsv11": obj.get("force_tlsv11"),
            "force_tlsv12": obj.get("force_tlsv12"),
            "force_tlsv13": obj.get("force_tlsv13"),
            "generate_certificates": obj.get("generate_certificates"),
            "gid": obj.get("gid"),
            "group": obj.get("group"),
            "guid_prefix": obj.get("guid_prefix"),
            "id": obj.get("id"),
            "idle_ping": obj.get("idle_ping"),
            "interface": obj.get("interface"),
            "level": obj.get("level"),
            "maxconn": obj.get("maxconn"),
            "mode": obj.get("mode"),
            "mss": obj.get("mss"),
            "name": obj.get("name"),
            "namespace": obj.get("namespace"),
            "nbconn": obj.get("nbconn"),
            "nice": obj.get("nice"),
            "no_alpn": obj.get("no_alpn"),
            "no_ca_names": obj.get("no_ca_names"),
            "no_sslv3": obj.get("no_sslv3"),
            "no_strict_sni": obj.get("no_strict_sni"),
            "no_tls_tickets": obj.get("no_tls_tickets"),
            "no_tlsv10": obj.get("no_tlsv10"),
            "no_tlsv11": obj.get("no_tlsv11"),
            "no_tlsv12": obj.get("no_tlsv12"),
            "no_tlsv13": obj.get("no_tlsv13"),
            "npn": obj.get("npn"),
            "prefer_client_ciphers": obj.get("prefer_client_ciphers"),
            "proto": obj.get("proto"),
            "quic-cc-algo": obj.get("quic-cc-algo"),
            "quic-force-retry": obj.get("quic-force-retry"),
            "quic-socket": obj.get("quic-socket"),
            "quic_cc_algo_burst_size": obj.get("quic_cc_algo_burst_size"),
            "quic_cc_algo_max_window": obj.get("quic_cc_algo_max_window"),
            "severity_output": obj.get("severity_output"),
            "sigalgs": obj.get("sigalgs"),
            "ssl": obj.get("ssl"),
            "ssl_cafile": obj.get("ssl_cafile"),
            "ssl_certificate": obj.get("ssl_certificate"),
            "ssl_max_ver": obj.get("ssl_max_ver"),
            "ssl_min_ver": obj.get("ssl_min_ver"),
            "sslv3": obj.get("sslv3"),
            "strict_sni": obj.get("strict_sni"),
            "tcp_user_timeout": obj.get("tcp_user_timeout"),
            "tfo": obj.get("tfo"),
            "thread": obj.get("thread"),
            "tls_ticket_keys": obj.get("tls_ticket_keys"),
            "tls_tickets": obj.get("tls_tickets"),
            "tlsv10": obj.get("tlsv10"),
            "tlsv11": obj.get("tlsv11"),
            "tlsv12": obj.get("tlsv12"),
            "tlsv13": obj.get("tlsv13"),
            "transparent": obj.get("transparent"),
            "uid": obj.get("uid"),
            "user": obj.get("user"),
            "v4v6": obj.get("v4v6"),
            "v6only": obj.get("v6only"),
            "verify": obj.get("verify")
        })
        return _obj


