# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Consul(BaseModel):
    """
    Consul server configuration
    """ # noqa: E501
    address: Annotated[str, Field(strict=True)]
    defaults: Optional[StrictStr] = Field(default=None, description="Name of the defaults section to be used in backends created by this service")
    description: Optional[StrictStr] = None
    enabled: StrictBool
    health_check_policy: Optional[StrictStr] = Field(default='none', description="Defines the health check conditions required for each node to be considered valid for the service.   none: all nodes are considered valid   any: a node is considered valid if any one health check is 'passing'   all: a node is considered valid if all health checks are 'passing'   min: a node is considered valid if the number of 'passing' checks is greater or equal to the 'health_check_policy_min' value.     If the node has less health checks configured then 'health_check_policy_min' it is considered invalid.")
    health_check_policy_min: Optional[StrictInt] = None
    id: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Auto generated ID.")
    mode: Optional[StrictStr] = 'http'
    name: Optional[StrictStr] = None
    namespace: Optional[StrictStr] = None
    port: Annotated[int, Field(le=65535, strict=True, ge=1)]
    retry_timeout: Annotated[int, Field(strict=True, ge=1)] = Field(description="Duration in seconds in-between data pulling requests to the consul server")
    server_slots_base: Optional[StrictInt] = None
    server_slots_growth_increment: Optional[StrictInt] = None
    server_slots_growth_type: Optional[StrictStr] = 'exponential'
    service_allowlist: Optional[List[Annotated[str, Field(strict=True)]]] = None
    service_denylist: Optional[List[Annotated[str, Field(strict=True)]]] = None
    service_name_regexp: Optional[StrictStr] = Field(default=None, description="Regular expression used to filter services by name.")
    token: Optional[Annotated[str, Field(strict=True)]] = None
    __properties: ClassVar[List[str]] = ["address", "defaults", "description", "enabled", "health_check_policy", "health_check_policy_min", "id", "mode", "name", "namespace", "port", "retry_timeout", "server_slots_base", "server_slots_growth_increment", "server_slots_growth_type", "service_allowlist", "service_denylist", "service_name_regexp", "token"]

    @field_validator('address')
    def address_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('health_check_policy')
    def health_check_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'any', 'all', 'min']):
            raise ValueError("must be one of enum values ('none', 'any', 'all', 'min')")
        return value

    @field_validator('id')
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['http', 'https']):
            raise ValueError("must be one of enum values ('http', 'https')")
        return value

    @field_validator('server_slots_growth_type')
    def server_slots_growth_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['linear', 'exponential']):
            raise ValueError("must be one of enum values ('linear', 'exponential')")
        return value

    @field_validator('token')
    def token_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Consul from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Consul from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "defaults": obj.get("defaults"),
            "description": obj.get("description"),
            "enabled": obj.get("enabled"),
            "health_check_policy": obj.get("health_check_policy") if obj.get("health_check_policy") is not None else 'none',
            "health_check_policy_min": obj.get("health_check_policy_min"),
            "id": obj.get("id"),
            "mode": obj.get("mode") if obj.get("mode") is not None else 'http',
            "name": obj.get("name"),
            "namespace": obj.get("namespace"),
            "port": obj.get("port"),
            "retry_timeout": obj.get("retry_timeout"),
            "server_slots_base": obj.get("server_slots_base"),
            "server_slots_growth_increment": obj.get("server_slots_growth_increment"),
            "server_slots_growth_type": obj.get("server_slots_growth_type") if obj.get("server_slots_growth_type") is not None else 'exponential',
            "service_allowlist": obj.get("service_allowlist"),
            "service_denylist": obj.get("service_denylist"),
            "service_name_regexp": obj.get("service_name_regexp"),
            "token": obj.get("token")
        })
        return _obj


