# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from haproxy_dataplane_v3.models.cookie_attr_inner import CookieAttrInner
from haproxy_dataplane_v3.models.cookie_domain_inner import CookieDomainInner
from typing import Optional, Set
from typing_extensions import Self

class Cookie(BaseModel):
    """
    Cookie
    """ # noqa: E501
    attr: Optional[List[CookieAttrInner]] = None
    domain: Optional[List[CookieDomainInner]] = None
    dynamic: Optional[StrictBool] = None
    httponly: Optional[StrictBool] = None
    indirect: Optional[StrictBool] = None
    maxidle: Optional[StrictInt] = None
    maxlife: Optional[StrictInt] = None
    name: Annotated[str, Field(strict=True)]
    nocache: Optional[StrictBool] = None
    postonly: Optional[StrictBool] = None
    preserve: Optional[StrictBool] = None
    secure: Optional[StrictBool] = None
    type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["attr", "domain", "dynamic", "httponly", "indirect", "maxidle", "maxlife", "name", "nocache", "postonly", "preserve", "secure", "type"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['rewrite', 'insert', 'prefix']):
            raise ValueError("must be one of enum values ('rewrite', 'insert', 'prefix')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Cookie from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attr (list)
        _items = []
        if self.attr:
            for _item_attr in self.attr:
                if _item_attr:
                    _items.append(_item_attr.to_dict())
            _dict['attr'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in domain (list)
        _items = []
        if self.domain:
            for _item_domain in self.domain:
                if _item_domain:
                    _items.append(_item_domain.to_dict())
            _dict['domain'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Cookie from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attr": [CookieAttrInner.from_dict(_item) for _item in obj["attr"]] if obj.get("attr") is not None else None,
            "domain": [CookieDomainInner.from_dict(_item) for _item in obj["domain"]] if obj.get("domain") is not None else None,
            "dynamic": obj.get("dynamic"),
            "httponly": obj.get("httponly"),
            "indirect": obj.get("indirect"),
            "maxidle": obj.get("maxidle"),
            "maxlife": obj.get("maxlife"),
            "name": obj.get("name"),
            "nocache": obj.get("nocache"),
            "postonly": obj.get("postonly"),
            "preserve": obj.get("preserve"),
            "secure": obj.get("secure"),
            "type": obj.get("type")
        })
        return _obj


