# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CrtLoad(BaseModel):
    """
    Loads a certificate from a store with options
    """ # noqa: E501
    acme: Optional[StrictStr] = Field(default=None, description="ACME section name to use")
    alias: Optional[StrictStr] = Field(default=None, description="Certificate alias")
    certificate: StrictStr = Field(description="Certificate filename")
    domains: Optional[List[StrictStr]] = Field(default=None, description="List of domains used to generate the certificate with ACME")
    issuer: Optional[StrictStr] = Field(default=None, description="OCSP issuer filename")
    key: Optional[StrictStr] = Field(default=None, description="Private key filename")
    metadata: Optional[Dict[str, Any]] = None
    ocsp: Optional[StrictStr] = Field(default=None, description="OCSP response filename")
    ocsp_update: Optional[StrictStr] = Field(default=None, description="Automatic OCSP response update")
    sctl: Optional[StrictStr] = Field(default=None, description="Signed Certificate Timestamp List filename")
    __properties: ClassVar[List[str]] = ["acme", "alias", "certificate", "domains", "issuer", "key", "metadata", "ocsp", "ocsp_update", "sctl"]

    @field_validator('ocsp_update')
    def ocsp_update_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CrtLoad from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CrtLoad from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acme": obj.get("acme"),
            "alias": obj.get("alias"),
            "certificate": obj.get("certificate"),
            "domains": obj.get("domains"),
            "issuer": obj.get("issuer"),
            "key": obj.get("key"),
            "metadata": obj.get("metadata"),
            "ocsp": obj.get("ocsp"),
            "ocsp_update": obj.get("ocsp_update"),
            "sctl": obj.get("sctl")
        })
        return _obj


