# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from haproxy_dataplane_v3.models.return_header import ReturnHeader
from typing import Optional, Set
from typing_extensions import Self

class HttpResponseRule(BaseModel):
    """
    HAProxy HTTP response rule configuration (corresponds to http-response directives)
    """ # noqa: E501
    acl_file: Optional[Annotated[str, Field(strict=True)]] = None
    acl_keyfmt: Optional[Annotated[str, Field(strict=True)]] = None
    bandwidth_limit_limit: Optional[StrictStr] = None
    bandwidth_limit_name: Optional[StrictStr] = None
    bandwidth_limit_period: Optional[StrictStr] = None
    cache_name: Optional[Annotated[str, Field(strict=True)]] = None
    capture_id: Optional[StrictInt] = None
    capture_sample: Optional[Annotated[str, Field(strict=True)]] = None
    cond: Optional[StrictStr] = None
    cond_test: Optional[StrictStr] = None
    deny_status: Optional[Annotated[int, Field(le=599, strict=True, ge=200)]] = None
    expr: Optional[StrictStr] = None
    hdr_format: Optional[StrictStr] = None
    hdr_match: Optional[StrictStr] = None
    hdr_method: Optional[StrictStr] = None
    hdr_name: Optional[StrictStr] = None
    log_level: Optional[StrictStr] = None
    lua_action: Optional[Annotated[str, Field(strict=True)]] = None
    lua_params: Optional[StrictStr] = None
    map_file: Optional[Annotated[str, Field(strict=True)]] = None
    map_keyfmt: Optional[Annotated[str, Field(strict=True)]] = None
    map_valuefmt: Optional[Annotated[str, Field(strict=True)]] = None
    mark_value: Optional[Annotated[str, Field(strict=True)]] = None
    metadata: Optional[Dict[str, Any]] = None
    nice_value: Optional[Annotated[int, Field(le=1024, strict=True, ge=-1024)]] = None
    redir_code: Optional[StrictInt] = None
    redir_option: Optional[StrictStr] = None
    redir_type: Optional[StrictStr] = None
    redir_value: Optional[Annotated[str, Field(strict=True)]] = None
    return_content: Optional[StrictStr] = None
    return_content_format: Optional[StrictStr] = None
    return_content_type: Optional[StrictStr] = None
    return_hdrs: Optional[List[ReturnHeader]] = None
    return_status_code: Optional[Annotated[int, Field(le=599, strict=True, ge=200)]] = None
    rst_ttl: Optional[StrictInt] = None
    sc_expr: Optional[StrictStr] = None
    sc_id: Optional[StrictInt] = None
    sc_idx: Optional[StrictInt] = None
    sc_int: Optional[StrictInt] = None
    spoe_engine: Optional[Annotated[str, Field(strict=True)]] = None
    spoe_group: Optional[Annotated[str, Field(strict=True)]] = None
    status: Optional[Annotated[int, Field(le=999, strict=True, ge=100)]] = None
    status_reason: Optional[StrictStr] = None
    strict_mode: Optional[StrictStr] = None
    timeout: Optional[StrictStr] = None
    timeout_type: Optional[StrictStr] = None
    tos_value: Optional[Annotated[str, Field(strict=True)]] = None
    track_sc_key: Optional[Annotated[str, Field(strict=True)]] = None
    track_sc_stick_counter: Optional[StrictInt] = None
    track_sc_table: Optional[Annotated[str, Field(strict=True)]] = None
    type: StrictStr
    var_expr: Optional[StrictStr] = None
    var_format: Optional[StrictStr] = None
    var_name: Optional[Annotated[str, Field(strict=True)]] = None
    var_scope: Optional[Annotated[str, Field(strict=True)]] = None
    wait_at_least: Optional[StrictInt] = None
    wait_time: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    __properties: ClassVar[List[str]] = ["acl_file", "acl_keyfmt", "bandwidth_limit_limit", "bandwidth_limit_name", "bandwidth_limit_period", "cache_name", "capture_id", "capture_sample", "cond", "cond_test", "deny_status", "expr", "hdr_format", "hdr_match", "hdr_method", "hdr_name", "log_level", "lua_action", "lua_params", "map_file", "map_keyfmt", "map_valuefmt", "mark_value", "metadata", "nice_value", "redir_code", "redir_option", "redir_type", "redir_value", "return_content", "return_content_format", "return_content_type", "return_hdrs", "return_status_code", "rst_ttl", "sc_expr", "sc_id", "sc_idx", "sc_int", "spoe_engine", "spoe_group", "status", "status_reason", "strict_mode", "timeout", "timeout_type", "tos_value", "track_sc_key", "track_sc_stick_counter", "track_sc_table", "type", "var_expr", "var_format", "var_name", "var_scope", "wait_at_least", "wait_time"]

    @field_validator('acl_file')
    def acl_file_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('acl_keyfmt')
    def acl_keyfmt_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('cache_name')
    def cache_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('capture_sample')
    def capture_sample_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('cond')
    def cond_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['if', 'unless']):
            raise ValueError("must be one of enum values ('if', 'unless')")
        return value

    @field_validator('log_level')
    def log_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['emerg', 'alert', 'crit', 'err', 'warning', 'notice', 'info', 'debug', 'silent']):
            raise ValueError("must be one of enum values ('emerg', 'alert', 'crit', 'err', 'warning', 'notice', 'info', 'debug', 'silent')")
        return value

    @field_validator('lua_action')
    def lua_action_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('map_file')
    def map_file_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('map_keyfmt')
    def map_keyfmt_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('map_valuefmt')
    def map_valuefmt_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('mark_value')
    def mark_value_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(0x[0-9A-Fa-f]+|[0-9]+)$", value):
            raise ValueError(r"must validate the regular expression /^(0x[0-9A-Fa-f]+|[0-9]+)$/")
        return value

    @field_validator('redir_type')
    def redir_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['location', 'prefix', 'scheme']):
            raise ValueError("must be one of enum values ('location', 'prefix', 'scheme')")
        return value

    @field_validator('redir_value')
    def redir_value_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('return_content_format')
    def return_content_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['default-errorfiles', 'errorfile', 'errorfiles', 'file', 'lf-file', 'string', 'lf-string']):
            raise ValueError("must be one of enum values ('default-errorfiles', 'errorfile', 'errorfiles', 'file', 'lf-file', 'string', 'lf-string')")
        return value

    @field_validator('spoe_engine')
    def spoe_engine_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('spoe_group')
    def spoe_group_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('strict_mode')
    def strict_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['on', 'off']):
            raise ValueError("must be one of enum values ('on', 'off')")
        return value

    @field_validator('timeout_type')
    def timeout_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['server', 'tunnel', 'client']):
            raise ValueError("must be one of enum values ('server', 'tunnel', 'client')")
        return value

    @field_validator('tos_value')
    def tos_value_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(0x[0-9A-Fa-f]+|[0-9]+)$", value):
            raise ValueError(r"must validate the regular expression /^(0x[0-9A-Fa-f]+|[0-9]+)$/")
        return value

    @field_validator('track_sc_key')
    def track_sc_key_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('track_sc_table')
    def track_sc_table_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['add-acl', 'add-header', 'allow', 'cache-store', 'capture', 'del-acl', 'del-header', 'del-map', 'deny', 'lua', 'pause', 'redirect', 'replace-header', 'replace-value', 'return', 'sc-add-gpc', 'sc-inc-gpc', 'sc-inc-gpc0', 'sc-inc-gpc1', 'sc-set-gpt', 'sc-set-gpt0', 'send-spoe-group', 'set-fc-mark', 'set-fc-tos', 'set-header', 'set-log-level', 'set-map', 'set-mark', 'set-nice', 'set-status', 'set-timeout', 'set-tos', 'set-var', 'set-var-fmt', 'silent-drop', 'strict-mode', 'track-sc', 'unset-var', 'wait-for-body', 'set-bandwidth-limit', 'do-log']):
            raise ValueError("must be one of enum values ('add-acl', 'add-header', 'allow', 'cache-store', 'capture', 'del-acl', 'del-header', 'del-map', 'deny', 'lua', 'pause', 'redirect', 'replace-header', 'replace-value', 'return', 'sc-add-gpc', 'sc-inc-gpc', 'sc-inc-gpc0', 'sc-inc-gpc1', 'sc-set-gpt', 'sc-set-gpt0', 'send-spoe-group', 'set-fc-mark', 'set-fc-tos', 'set-header', 'set-log-level', 'set-map', 'set-mark', 'set-nice', 'set-status', 'set-timeout', 'set-tos', 'set-var', 'set-var-fmt', 'silent-drop', 'strict-mode', 'track-sc', 'unset-var', 'wait-for-body', 'set-bandwidth-limit', 'do-log')")
        return value

    @field_validator('var_name')
    def var_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('var_scope')
    def var_scope_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HttpResponseRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in return_hdrs (list)
        _items = []
        if self.return_hdrs:
            for _item_return_hdrs in self.return_hdrs:
                if _item_return_hdrs:
                    _items.append(_item_return_hdrs.to_dict())
            _dict['return_hdrs'] = _items
        # set to None if capture_id (nullable) is None
        # and model_fields_set contains the field
        if self.capture_id is None and "capture_id" in self.model_fields_set:
            _dict['capture_id'] = None

        # set to None if deny_status (nullable) is None
        # and model_fields_set contains the field
        if self.deny_status is None and "deny_status" in self.model_fields_set:
            _dict['deny_status'] = None

        # set to None if redir_code (nullable) is None
        # and model_fields_set contains the field
        if self.redir_code is None and "redir_code" in self.model_fields_set:
            _dict['redir_code'] = None

        # set to None if return_content_type (nullable) is None
        # and model_fields_set contains the field
        if self.return_content_type is None and "return_content_type" in self.model_fields_set:
            _dict['return_content_type'] = None

        # set to None if return_status_code (nullable) is None
        # and model_fields_set contains the field
        if self.return_status_code is None and "return_status_code" in self.model_fields_set:
            _dict['return_status_code'] = None

        # set to None if sc_int (nullable) is None
        # and model_fields_set contains the field
        if self.sc_int is None and "sc_int" in self.model_fields_set:
            _dict['sc_int'] = None

        # set to None if track_sc_stick_counter (nullable) is None
        # and model_fields_set contains the field
        if self.track_sc_stick_counter is None and "track_sc_stick_counter" in self.model_fields_set:
            _dict['track_sc_stick_counter'] = None

        # set to None if wait_at_least (nullable) is None
        # and model_fields_set contains the field
        if self.wait_at_least is None and "wait_at_least" in self.model_fields_set:
            _dict['wait_at_least'] = None

        # set to None if wait_time (nullable) is None
        # and model_fields_set contains the field
        if self.wait_time is None and "wait_time" in self.model_fields_set:
            _dict['wait_time'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HttpResponseRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acl_file": obj.get("acl_file"),
            "acl_keyfmt": obj.get("acl_keyfmt"),
            "bandwidth_limit_limit": obj.get("bandwidth_limit_limit"),
            "bandwidth_limit_name": obj.get("bandwidth_limit_name"),
            "bandwidth_limit_period": obj.get("bandwidth_limit_period"),
            "cache_name": obj.get("cache_name"),
            "capture_id": obj.get("capture_id"),
            "capture_sample": obj.get("capture_sample"),
            "cond": obj.get("cond"),
            "cond_test": obj.get("cond_test"),
            "deny_status": obj.get("deny_status"),
            "expr": obj.get("expr"),
            "hdr_format": obj.get("hdr_format"),
            "hdr_match": obj.get("hdr_match"),
            "hdr_method": obj.get("hdr_method"),
            "hdr_name": obj.get("hdr_name"),
            "log_level": obj.get("log_level"),
            "lua_action": obj.get("lua_action"),
            "lua_params": obj.get("lua_params"),
            "map_file": obj.get("map_file"),
            "map_keyfmt": obj.get("map_keyfmt"),
            "map_valuefmt": obj.get("map_valuefmt"),
            "mark_value": obj.get("mark_value"),
            "metadata": obj.get("metadata"),
            "nice_value": obj.get("nice_value"),
            "redir_code": obj.get("redir_code"),
            "redir_option": obj.get("redir_option"),
            "redir_type": obj.get("redir_type"),
            "redir_value": obj.get("redir_value"),
            "return_content": obj.get("return_content"),
            "return_content_format": obj.get("return_content_format"),
            "return_content_type": obj.get("return_content_type"),
            "return_hdrs": [ReturnHeader.from_dict(_item) for _item in obj["return_hdrs"]] if obj.get("return_hdrs") is not None else None,
            "return_status_code": obj.get("return_status_code"),
            "rst_ttl": obj.get("rst_ttl"),
            "sc_expr": obj.get("sc_expr"),
            "sc_id": obj.get("sc_id"),
            "sc_idx": obj.get("sc_idx"),
            "sc_int": obj.get("sc_int"),
            "spoe_engine": obj.get("spoe_engine"),
            "spoe_group": obj.get("spoe_group"),
            "status": obj.get("status"),
            "status_reason": obj.get("status_reason"),
            "strict_mode": obj.get("strict_mode"),
            "timeout": obj.get("timeout"),
            "timeout_type": obj.get("timeout_type"),
            "tos_value": obj.get("tos_value"),
            "track_sc_key": obj.get("track_sc_key"),
            "track_sc_stick_counter": obj.get("track_sc_stick_counter"),
            "track_sc_table": obj.get("track_sc_table"),
            "type": obj.get("type"),
            "var_expr": obj.get("var_expr"),
            "var_format": obj.get("var_format"),
            "var_name": obj.get("var_name"),
            "var_scope": obj.get("var_scope"),
            "wait_at_least": obj.get("wait_at_least"),
            "wait_time": obj.get("wait_time")
        })
        return _obj


