from enum import Enum


class HTTPResponseRuleType(str, Enum):
    ADD_ACL = "add-acl"
    ADD_HEADER = "add-header"
    ALLOW = "allow"
    CACHE_STORE = "cache-store"
    CAPTURE = "capture"
    DEL_ACL = "del-acl"
    DEL_HEADER = "del-header"
    DEL_MAP = "del-map"
    DENY = "deny"
    DO_LOG = "do-log"
    LUA = "lua"
    PAUSE = "pause"
    REDIRECT = "redirect"
    REPLACE_HEADER = "replace-header"
    REPLACE_VALUE = "replace-value"
    RETURN = "return"
    SC_ADD_GPC = "sc-add-gpc"
    SC_INC_GPC = "sc-inc-gpc"
    SC_INC_GPC0 = "sc-inc-gpc0"
    SC_INC_GPC1 = "sc-inc-gpc1"
    SC_SET_GPT = "sc-set-gpt"
    SC_SET_GPT0 = "sc-set-gpt0"
    SEND_SPOE_GROUP = "send-spoe-group"
    SET_BANDWIDTH_LIMIT = "set-bandwidth-limit"
    SET_FC_MARK = "set-fc-mark"
    SET_FC_TOS = "set-fc-tos"
    SET_HEADER = "set-header"
    SET_LOG_LEVEL = "set-log-level"
    SET_MAP = "set-map"
    SET_MARK = "set-mark"
    SET_NICE = "set-nice"
    SET_STATUS = "set-status"
    SET_TIMEOUT = "set-timeout"
    SET_TOS = "set-tos"
    SET_VAR = "set-var"
    SET_VAR_FMT = "set-var-fmt"
    SILENT_DROP = "silent-drop"
    STRICT_MODE = "strict-mode"
    TRACK_SC = "track-sc"
    UNSET_VAR = "unset-var"
    WAIT_FOR_BODY = "wait-for-body"

    def __str__(self) -> str:
        return str(self.value)
