# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from haproxy_dataplane_v3.models.return_header import ReturnHeader
from typing import Optional, Set
from typing_extensions import Self

class HttpErrorRule(BaseModel):
    """
    HAProxy HTTP error rule configuration (corresponds to http-error directives)
    """ # noqa: E501
    metadata: Optional[Dict[str, Any]] = None
    return_content: Optional[StrictStr] = None
    return_content_format: Optional[StrictStr] = None
    return_content_type: Optional[StrictStr] = None
    return_hdrs: Optional[List[ReturnHeader]] = None
    status: StrictInt
    type: StrictStr
    __properties: ClassVar[List[str]] = ["metadata", "return_content", "return_content_format", "return_content_type", "return_hdrs", "status", "type"]

    @field_validator('return_content_format')
    def return_content_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['default-errorfiles', 'errorfile', 'errorfiles', 'file', 'lf-file', 'string', 'lf-string']):
            raise ValueError("must be one of enum values ('default-errorfiles', 'errorfile', 'errorfiles', 'file', 'lf-file', 'string', 'lf-string')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['status']):
            raise ValueError("must be one of enum values ('status')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HttpErrorRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in return_hdrs (list)
        _items = []
        if self.return_hdrs:
            for _item_return_hdrs in self.return_hdrs:
                if _item_return_hdrs:
                    _items.append(_item_return_hdrs.to_dict())
            _dict['return_hdrs'] = _items
        # set to None if return_content_type (nullable) is None
        # and model_fields_set contains the field
        if self.return_content_type is None and "return_content_type" in self.model_fields_set:
            _dict['return_content_type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HttpErrorRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "metadata": obj.get("metadata"),
            "return_content": obj.get("return_content"),
            "return_content_format": obj.get("return_content_format"),
            "return_content_type": obj.get("return_content_type"),
            "return_hdrs": [ReturnHeader.from_dict(_item) for _item in obj["return_hdrs"]] if obj.get("return_hdrs") is not None else None,
            "status": obj.get("status"),
            "type": obj.get("type")
        })
        return _obj


