# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from haproxy_dataplane_v3.models.info_system_cpu_info import InfoSystemCpuInfo
from haproxy_dataplane_v3.models.info_system_mem_info import InfoSystemMemInfo
from typing import Optional, Set
from typing_extensions import Self

class InfoSystem(BaseModel):
    """
    InfoSystem
    """ # noqa: E501
    cpu_info: Optional[InfoSystemCpuInfo] = None
    hostname: Optional[StrictStr] = Field(default=None, description="Hostname where the HAProxy is running")
    mem_info: Optional[InfoSystemMemInfo] = None
    os_string: Optional[StrictStr] = Field(default=None, description="OS string")
    time: Optional[StrictInt] = Field(default=None, description="Current time in milliseconds since Epoch.")
    uptime: Optional[StrictInt] = Field(default=None, description="System uptime")
    __properties: ClassVar[List[str]] = ["cpu_info", "hostname", "mem_info", "os_string", "time", "uptime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InfoSystem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cpu_info
        if self.cpu_info:
            _dict['cpu_info'] = self.cpu_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mem_info
        if self.mem_info:
            _dict['mem_info'] = self.mem_info.to_dict()
        # set to None if uptime (nullable) is None
        # and model_fields_set contains the field
        if self.uptime is None and "uptime" in self.model_fields_set:
            _dict['uptime'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InfoSystem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cpu_info": InfoSystemCpuInfo.from_dict(obj["cpu_info"]) if obj.get("cpu_info") is not None else None,
            "hostname": obj.get("hostname"),
            "mem_info": InfoSystemMemInfo.from_dict(obj["mem_info"]) if obj.get("mem_info") is not None else None,
            "os_string": obj.get("os_string"),
            "time": obj.get("time"),
            "uptime": obj.get("uptime")
        })
        return _obj


