# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class PerformanceOptions(BaseModel):
    """
    PerformanceOptions
    """ # noqa: E501
    busy_polling: Optional[StrictBool] = None
    max_spread_checks: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    maxcompcpuusage: Optional[StrictInt] = None
    maxcomprate: Optional[StrictInt] = None
    maxconn: Optional[StrictInt] = None
    maxconnrate: Optional[StrictInt] = None
    maxpipes: Optional[StrictInt] = None
    maxsessrate: Optional[StrictInt] = None
    maxzlibmem: Optional[StrictInt] = None
    noepoll: Optional[StrictBool] = None
    noevports: Optional[StrictBool] = None
    nogetaddrinfo: Optional[StrictBool] = None
    nokqueue: Optional[StrictBool] = None
    nopoll: Optional[StrictBool] = None
    noreuseport: Optional[StrictBool] = None
    nosplice: Optional[StrictBool] = None
    profiling_memory: Optional[StrictStr] = None
    profiling_tasks: Optional[StrictStr] = None
    server_state_base: Optional[Annotated[str, Field(strict=True)]] = None
    server_state_file: Optional[Annotated[str, Field(strict=True)]] = None
    spread_checks: Optional[StrictInt] = None
    thread_hard_limit: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["busy_polling", "max_spread_checks", "maxcompcpuusage", "maxcomprate", "maxconn", "maxconnrate", "maxpipes", "maxsessrate", "maxzlibmem", "noepoll", "noevports", "nogetaddrinfo", "nokqueue", "nopoll", "noreuseport", "nosplice", "profiling_memory", "profiling_tasks", "server_state_base", "server_state_file", "spread_checks", "thread_hard_limit"]

    @field_validator('profiling_memory')
    def profiling_memory_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    @field_validator('profiling_tasks')
    def profiling_tasks_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['auto', 'enabled', 'disabled']):
            raise ValueError("must be one of enum values ('auto', 'enabled', 'disabled')")
        return value

    @field_validator('server_state_base')
    def server_state_base_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('server_state_file')
    def server_state_file_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PerformanceOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if max_spread_checks (nullable) is None
        # and model_fields_set contains the field
        if self.max_spread_checks is None and "max_spread_checks" in self.model_fields_set:
            _dict['max_spread_checks'] = None

        # set to None if thread_hard_limit (nullable) is None
        # and model_fields_set contains the field
        if self.thread_hard_limit is None and "thread_hard_limit" in self.model_fields_set:
            _dict['thread_hard_limit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PerformanceOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "busy_polling": obj.get("busy_polling"),
            "max_spread_checks": obj.get("max_spread_checks"),
            "maxcompcpuusage": obj.get("maxcompcpuusage"),
            "maxcomprate": obj.get("maxcomprate"),
            "maxconn": obj.get("maxconn"),
            "maxconnrate": obj.get("maxconnrate"),
            "maxpipes": obj.get("maxpipes"),
            "maxsessrate": obj.get("maxsessrate"),
            "maxzlibmem": obj.get("maxzlibmem"),
            "noepoll": obj.get("noepoll"),
            "noevports": obj.get("noevports"),
            "nogetaddrinfo": obj.get("nogetaddrinfo"),
            "nokqueue": obj.get("nokqueue"),
            "nopoll": obj.get("nopoll"),
            "noreuseport": obj.get("noreuseport"),
            "nosplice": obj.get("nosplice"),
            "profiling_memory": obj.get("profiling_memory"),
            "profiling_tasks": obj.get("profiling_tasks"),
            "server_state_base": obj.get("server_state_base"),
            "server_state_file": obj.get("server_state_file"),
            "spread_checks": obj.get("spread_checks"),
            "thread_hard_limit": obj.get("thread_hard_limit")
        })
        return _obj


