# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Program(BaseModel):
    """
    HAProxy program configuration
    """ # noqa: E501
    command: StrictStr = Field(description="The command to be run, with flags and options.")
    group: Optional[StrictStr] = Field(default=None, description="The group to run the command as, if different than the HAProxy group.")
    metadata: Optional[Dict[str, Any]] = None
    name: Annotated[str, Field(strict=True)]
    start_on_reload: Optional[StrictStr] = Field(default=None, description="HAProxy stops and recreates child programs at reload.", alias="start-on-reload")
    user: Optional[StrictStr] = Field(default=None, description="The user to run the command as, if different than the HAProxy user.")
    __properties: ClassVar[List[str]] = ["command", "group", "metadata", "name", "start-on-reload", "user"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Za-z0-9-_.:]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9-_.:]+$/")
        return value

    @field_validator('start_on_reload')
    def start_on_reload_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'disabled']):
            raise ValueError("must be one of enum values ('enabled', 'disabled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Program from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Program from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "command": obj.get("command"),
            "group": obj.get("group"),
            "metadata": obj.get("metadata"),
            "name": obj.get("name"),
            "start-on-reload": obj.get("start-on-reload"),
            "user": obj.get("user")
        })
        return _obj


