# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SslOcspUpdate(BaseModel):
    """
    SSL OCSP Update
    """ # noqa: E501
    cert_id: Optional[StrictStr] = None
    failures: Optional[StrictInt] = None
    last_update: Optional[StrictStr] = None
    last_update_status: Optional[StrictInt] = None
    last_update_status_str: Optional[StrictStr] = None
    next_update: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    successes: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["cert_id", "failures", "last_update", "last_update_status", "last_update_status_str", "next_update", "path", "successes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SslOcspUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SslOcspUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cert_id": obj.get("cert_id"),
            "failures": obj.get("failures"),
            "last_update": obj.get("last_update"),
            "last_update_status": obj.get("last_update_status"),
            "last_update_status_str": obj.get("last_update_status_str"),
            "next_update": obj.get("next_update"),
            "path": obj.get("path"),
            "successes": obj.get("successes")
        })
        return _obj


