# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SslCertificate(BaseModel):
    """
    A file containing one or more SSL/TLS certificates and keys
    """ # noqa: E501
    algorithm: Optional[StrictStr] = None
    authority_key_id: Optional[StrictStr] = None
    chain_issuer: Optional[StrictStr] = None
    chain_subject: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    domains: Optional[StrictStr] = None
    file: Optional[StrictStr] = None
    ip_addresses: Optional[StrictStr] = None
    issuers: Optional[StrictStr] = None
    not_after: Optional[datetime] = None
    not_before: Optional[datetime] = None
    serial: Optional[StrictStr] = None
    sha1_finger_print: Optional[StrictStr] = None
    sha256_finger_print: Optional[StrictStr] = None
    size: Optional[StrictInt] = Field(default=None, description="File size in bytes.")
    status: Optional[StrictStr] = Field(default=None, description="Only set when using the runtime API.")
    storage_name: Optional[StrictStr] = None
    subject: Optional[StrictStr] = None
    subject_alternative_names: Optional[StrictStr] = None
    subject_key_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["algorithm", "authority_key_id", "chain_issuer", "chain_subject", "description", "domains", "file", "ip_addresses", "issuers", "not_after", "not_before", "serial", "sha1_finger_print", "sha256_finger_print", "size", "status", "storage_name", "subject", "subject_alternative_names", "subject_key_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SslCertificate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "domains",
            "ip_addresses",
            "issuers",
            "not_after",
            "not_before",
            "size",
            "status",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if not_after (nullable) is None
        # and model_fields_set contains the field
        if self.not_after is None and "not_after" in self.model_fields_set:
            _dict['not_after'] = None

        # set to None if not_before (nullable) is None
        # and model_fields_set contains the field
        if self.not_before is None and "not_before" in self.model_fields_set:
            _dict['not_before'] = None

        # set to None if size (nullable) is None
        # and model_fields_set contains the field
        if self.size is None and "size" in self.model_fields_set:
            _dict['size'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SslCertificate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "algorithm": obj.get("algorithm"),
            "authority_key_id": obj.get("authority_key_id"),
            "chain_issuer": obj.get("chain_issuer"),
            "chain_subject": obj.get("chain_subject"),
            "description": obj.get("description"),
            "domains": obj.get("domains"),
            "file": obj.get("file"),
            "ip_addresses": obj.get("ip_addresses"),
            "issuers": obj.get("issuers"),
            "not_after": obj.get("not_after"),
            "not_before": obj.get("not_before"),
            "serial": obj.get("serial"),
            "sha1_finger_print": obj.get("sha1_finger_print"),
            "sha256_finger_print": obj.get("sha256_finger_print"),
            "size": obj.get("size"),
            "status": obj.get("status"),
            "storage_name": obj.get("storage_name"),
            "subject": obj.get("subject"),
            "subject_alternative_names": obj.get("subject_alternative_names"),
            "subject_key_id": obj.get("subject_key_id")
        })
        return _obj


