from enum import Enum


class TCPRequestRuleAction(str, Enum):
    ACCEPT = "accept"
    ATTACH_SRV = "attach-srv"
    CAPTURE = "capture"
    DO_LOG = "do-log"
    DO_RESOLVE = "do-resolve"
    EXPECT_NETSCALER_CIP = "expect-netscaler-cip"
    EXPECT_PROXY = "expect-proxy"
    LUA = "lua"
    REJECT = "reject"
    SC_ADD_GPC = "sc-add-gpc"
    SC_INC_GPC = "sc-inc-gpc"
    SC_INC_GPC0 = "sc-inc-gpc0"
    SC_INC_GPC1 = "sc-inc-gpc1"
    SC_SET_GPT = "sc-set-gpt"
    SC_SET_GPT0 = "sc-set-gpt0"
    SEND_SPOE_GROUP = "send-spoe-group"
    SET_BANDWIDTH_LIMIT = "set-bandwidth-limit"
    SET_BC_MARK = "set-bc-mark"
    SET_BC_TOS = "set-bc-tos"
    SET_DST = "set-dst"
    SET_DST_PORT = "set-dst-port"
    SET_FC_MARK = "set-fc-mark"
    SET_FC_TOS = "set-fc-tos"
    SET_LOG_LEVEL = "set-log-level"
    SET_MARK = "set-mark"
    SET_NICE = "set-nice"
    SET_PRIORITY_CLASS = "set-priority-class"
    SET_PRIORITY_OFFSET = "set-priority-offset"
    SET_RETRIES = "set-retries"
    SET_SRC = "set-src"
    SET_SRC_PORT = "set-src-port"
    SET_TOS = "set-tos"
    SET_VAR = "set-var"
    SET_VAR_FMT = "set-var-fmt"
    SILENT_DROP = "silent-drop"
    SWITCH_MODE = "switch-mode"
    TRACK_SC = "track-sc"
    UNSET_VAR = "unset-var"
    USE_SERVICE = "use-service"

    def __str__(self) -> str:
        return str(self.value)
