# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TcpResponseRule(BaseModel):
    """
    HAProxy TCP Response Rule configuration (corresponds to tcp-response)
    """ # noqa: E501
    action: Optional[StrictStr] = None
    bandwidth_limit_limit: Optional[StrictStr] = None
    bandwidth_limit_name: Optional[StrictStr] = None
    bandwidth_limit_period: Optional[StrictStr] = None
    cond: Optional[StrictStr] = None
    cond_test: Optional[StrictStr] = None
    expr: Optional[StrictStr] = None
    log_level: Optional[StrictStr] = None
    lua_action: Optional[Annotated[str, Field(strict=True)]] = None
    lua_params: Optional[StrictStr] = None
    mark_value: Optional[Annotated[str, Field(strict=True)]] = None
    metadata: Optional[Dict[str, Any]] = None
    nice_value: Optional[Annotated[int, Field(le=1024, strict=True, ge=-1024)]] = None
    rst_ttl: Optional[StrictInt] = None
    sc_expr: Optional[StrictStr] = None
    sc_id: Optional[StrictInt] = None
    sc_idx: Optional[StrictInt] = None
    sc_int: Optional[StrictInt] = None
    spoe_engine: Optional[Annotated[str, Field(strict=True)]] = None
    spoe_group: Optional[Annotated[str, Field(strict=True)]] = None
    timeout: Optional[StrictInt] = None
    tos_value: Optional[Annotated[str, Field(strict=True)]] = None
    type: StrictStr
    var_format: Optional[StrictStr] = None
    var_name: Optional[Annotated[str, Field(strict=True)]] = None
    var_scope: Optional[Annotated[str, Field(strict=True)]] = None
    __properties: ClassVar[List[str]] = ["action", "bandwidth_limit_limit", "bandwidth_limit_name", "bandwidth_limit_period", "cond", "cond_test", "expr", "log_level", "lua_action", "lua_params", "mark_value", "metadata", "nice_value", "rst_ttl", "sc_expr", "sc_id", "sc_idx", "sc_int", "spoe_engine", "spoe_group", "timeout", "tos_value", "type", "var_format", "var_name", "var_scope"]

    @field_validator('action')
    def action_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['accept', 'close', 'lua', 'reject', 'sc-add-gpc', 'sc-inc-gpc', 'sc-inc-gpc0', 'sc-inc-gpc1', 'sc-set-gpt', 'sc-set-gpt0', 'send-spoe-group', 'set-bandwidth-limit', 'set-fc-mark', 'set-fc-tos', 'set-log-level', 'set-mark', 'set-nice', 'set-tos', 'set-var', 'set-var-fmt', 'silent-drop', 'unset-var', 'do-log']):
            raise ValueError("must be one of enum values ('accept', 'close', 'lua', 'reject', 'sc-add-gpc', 'sc-inc-gpc', 'sc-inc-gpc0', 'sc-inc-gpc1', 'sc-set-gpt', 'sc-set-gpt0', 'send-spoe-group', 'set-bandwidth-limit', 'set-fc-mark', 'set-fc-tos', 'set-log-level', 'set-mark', 'set-nice', 'set-tos', 'set-var', 'set-var-fmt', 'silent-drop', 'unset-var', 'do-log')")
        return value

    @field_validator('cond')
    def cond_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['if', 'unless']):
            raise ValueError("must be one of enum values ('if', 'unless')")
        return value

    @field_validator('log_level')
    def log_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['emerg', 'alert', 'crit', 'err', 'warning', 'notice', 'info', 'debug', 'silent']):
            raise ValueError("must be one of enum values ('emerg', 'alert', 'crit', 'err', 'warning', 'notice', 'info', 'debug', 'silent')")
        return value

    @field_validator('lua_action')
    def lua_action_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('mark_value')
    def mark_value_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(0x[0-9A-Fa-f]+|[0-9]+)$", value):
            raise ValueError(r"must validate the regular expression /^(0x[0-9A-Fa-f]+|[0-9]+)$/")
        return value

    @field_validator('spoe_engine')
    def spoe_engine_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('spoe_group')
    def spoe_group_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('tos_value')
    def tos_value_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(0x[0-9A-Fa-f]+|[0-9]+)$", value):
            raise ValueError(r"must validate the regular expression /^(0x[0-9A-Fa-f]+|[0-9]+)$/")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['content', 'inspect-delay']):
            raise ValueError("must be one of enum values ('content', 'inspect-delay')")
        return value

    @field_validator('var_name')
    def var_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    @field_validator('var_scope')
    def var_scope_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[^\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[^\s]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TcpResponseRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if sc_int (nullable) is None
        # and model_fields_set contains the field
        if self.sc_int is None and "sc_int" in self.model_fields_set:
            _dict['sc_int'] = None

        # set to None if timeout (nullable) is None
        # and model_fields_set contains the field
        if self.timeout is None and "timeout" in self.model_fields_set:
            _dict['timeout'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TcpResponseRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "bandwidth_limit_limit": obj.get("bandwidth_limit_limit"),
            "bandwidth_limit_name": obj.get("bandwidth_limit_name"),
            "bandwidth_limit_period": obj.get("bandwidth_limit_period"),
            "cond": obj.get("cond"),
            "cond_test": obj.get("cond_test"),
            "expr": obj.get("expr"),
            "log_level": obj.get("log_level"),
            "lua_action": obj.get("lua_action"),
            "lua_params": obj.get("lua_params"),
            "mark_value": obj.get("mark_value"),
            "metadata": obj.get("metadata"),
            "nice_value": obj.get("nice_value"),
            "rst_ttl": obj.get("rst_ttl"),
            "sc_expr": obj.get("sc_expr"),
            "sc_id": obj.get("sc_id"),
            "sc_idx": obj.get("sc_idx"),
            "sc_int": obj.get("sc_int"),
            "spoe_engine": obj.get("spoe_engine"),
            "spoe_group": obj.get("spoe_group"),
            "timeout": obj.get("timeout"),
            "tos_value": obj.get("tos_value"),
            "type": obj.get("type"),
            "var_format": obj.get("var_format"),
            "var_name": obj.get("var_name"),
            "var_scope": obj.get("var_scope")
        })
        return _obj


