# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TuneVarsOptions(BaseModel):
    """
    TuneVarsOptions
    """ # noqa: E501
    global_max_size: Optional[StrictInt] = None
    proc_max_size: Optional[StrictInt] = None
    reqres_max_size: Optional[StrictInt] = None
    sess_max_size: Optional[StrictInt] = None
    txn_max_size: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["global_max_size", "proc_max_size", "reqres_max_size", "sess_max_size", "txn_max_size"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TuneVarsOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if global_max_size (nullable) is None
        # and model_fields_set contains the field
        if self.global_max_size is None and "global_max_size" in self.model_fields_set:
            _dict['global_max_size'] = None

        # set to None if proc_max_size (nullable) is None
        # and model_fields_set contains the field
        if self.proc_max_size is None and "proc_max_size" in self.model_fields_set:
            _dict['proc_max_size'] = None

        # set to None if reqres_max_size (nullable) is None
        # and model_fields_set contains the field
        if self.reqres_max_size is None and "reqres_max_size" in self.model_fields_set:
            _dict['reqres_max_size'] = None

        # set to None if sess_max_size (nullable) is None
        # and model_fields_set contains the field
        if self.sess_max_size is None and "sess_max_size" in self.model_fields_set:
            _dict['sess_max_size'] = None

        # set to None if txn_max_size (nullable) is None
        # and model_fields_set contains the field
        if self.txn_max_size is None and "txn_max_size" in self.model_fields_set:
            _dict['txn_max_size'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TuneVarsOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "global_max_size": obj.get("global_max_size"),
            "proc_max_size": obj.get("proc_max_size"),
            "reqres_max_size": obj.get("reqres_max_size"),
            "sess_max_size": obj.get("sess_max_size"),
            "txn_max_size": obj.get("txn_max_size")
        })
        return _obj


