# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TuneBufferOptions(BaseModel):
    """
    TuneBufferOptions
    """ # noqa: E501
    buffers_limit: Optional[StrictInt] = None
    buffers_reserve: Optional[Annotated[int, Field(strict=True, ge=2)]] = None
    bufsize: Optional[StrictInt] = None
    bufsize_small: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    pipesize: Optional[StrictInt] = None
    rcvbuf_backend: Optional[StrictInt] = None
    rcvbuf_client: Optional[StrictInt] = None
    rcvbuf_frontend: Optional[StrictInt] = None
    rcvbuf_server: Optional[StrictInt] = None
    recv_enough: Optional[StrictInt] = None
    sndbuf_backend: Optional[StrictInt] = None
    sndbuf_client: Optional[StrictInt] = None
    sndbuf_frontend: Optional[StrictInt] = None
    sndbuf_server: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["buffers_limit", "buffers_reserve", "bufsize", "bufsize_small", "pipesize", "rcvbuf_backend", "rcvbuf_client", "rcvbuf_frontend", "rcvbuf_server", "recv_enough", "sndbuf_backend", "sndbuf_client", "sndbuf_frontend", "sndbuf_server"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TuneBufferOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if buffers_limit (nullable) is None
        # and model_fields_set contains the field
        if self.buffers_limit is None and "buffers_limit" in self.model_fields_set:
            _dict['buffers_limit'] = None

        # set to None if bufsize_small (nullable) is None
        # and model_fields_set contains the field
        if self.bufsize_small is None and "bufsize_small" in self.model_fields_set:
            _dict['bufsize_small'] = None

        # set to None if rcvbuf_backend (nullable) is None
        # and model_fields_set contains the field
        if self.rcvbuf_backend is None and "rcvbuf_backend" in self.model_fields_set:
            _dict['rcvbuf_backend'] = None

        # set to None if rcvbuf_client (nullable) is None
        # and model_fields_set contains the field
        if self.rcvbuf_client is None and "rcvbuf_client" in self.model_fields_set:
            _dict['rcvbuf_client'] = None

        # set to None if rcvbuf_frontend (nullable) is None
        # and model_fields_set contains the field
        if self.rcvbuf_frontend is None and "rcvbuf_frontend" in self.model_fields_set:
            _dict['rcvbuf_frontend'] = None

        # set to None if rcvbuf_server (nullable) is None
        # and model_fields_set contains the field
        if self.rcvbuf_server is None and "rcvbuf_server" in self.model_fields_set:
            _dict['rcvbuf_server'] = None

        # set to None if sndbuf_backend (nullable) is None
        # and model_fields_set contains the field
        if self.sndbuf_backend is None and "sndbuf_backend" in self.model_fields_set:
            _dict['sndbuf_backend'] = None

        # set to None if sndbuf_client (nullable) is None
        # and model_fields_set contains the field
        if self.sndbuf_client is None and "sndbuf_client" in self.model_fields_set:
            _dict['sndbuf_client'] = None

        # set to None if sndbuf_frontend (nullable) is None
        # and model_fields_set contains the field
        if self.sndbuf_frontend is None and "sndbuf_frontend" in self.model_fields_set:
            _dict['sndbuf_frontend'] = None

        # set to None if sndbuf_server (nullable) is None
        # and model_fields_set contains the field
        if self.sndbuf_server is None and "sndbuf_server" in self.model_fields_set:
            _dict['sndbuf_server'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TuneBufferOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "buffers_limit": obj.get("buffers_limit"),
            "buffers_reserve": obj.get("buffers_reserve"),
            "bufsize": obj.get("bufsize"),
            "bufsize_small": obj.get("bufsize_small"),
            "pipesize": obj.get("pipesize"),
            "rcvbuf_backend": obj.get("rcvbuf_backend"),
            "rcvbuf_client": obj.get("rcvbuf_client"),
            "rcvbuf_frontend": obj.get("rcvbuf_frontend"),
            "rcvbuf_server": obj.get("rcvbuf_server"),
            "recv_enough": obj.get("recv_enough"),
            "sndbuf_backend": obj.get("sndbuf_backend"),
            "sndbuf_client": obj.get("sndbuf_client"),
            "sndbuf_frontend": obj.get("sndbuf_frontend"),
            "sndbuf_server": obj.get("sndbuf_server")
        })
        return _obj


