{{- if .Values.rbac.create }}
{{- /* Merge watched resources from libraries */ -}}
{{- $mergedLibraries := include "haproxy-template-ic.mergeLibraries" . | fromYaml }}
{{- $allWatchedResources := merge ($mergedLibraries.watchedResources | default dict) (.Values.controller.config.watchedResources | default dict) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "haproxy-template-ic.fullname" . }}
  labels:
    {{- include "haproxy-template-ic.labels" . | nindent 4 }}
rules:
  # Watched resources from configuration and libraries
  {{- range $name, $resource := $allWatchedResources }}
  - apiGroups:
      {{- if eq $resource.apiVersion "v1" }}
      - ""
      {{- else }}
      - {{ $resource.apiVersion | regexFind "^[^/]+" }}
      {{- end }}
    resources:
      - {{ $resource.resources }}
    verbs: ["get", "list", "watch"]
  {{- end }}
  # Additional core resources
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "list", "watch"]
  # Leader election (coordination.k8s.io/v1)
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
  # HAProxyTemplateConfig CRD
  - apiGroups: ["haproxy-template-ic.github.io"]
    resources: ["haproxytemplateconfigs"]
    verbs: ["get", "list", "watch"]
{{- end }}
