{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "haproxy-template-ic.fullname" . }}
  labels:
    {{- include "haproxy-template-ic.labels" . | nindent 4 }}
rules:
  # Core resources
  - apiGroups: [""]
    resources: ["services", "configmaps", "namespaces", "secrets", "pods"]
    verbs: ["get", "list", "watch"]
  # Ingress resources
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  # EndpointSlice resources
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
{{- end }}
