apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.controller.configmapName }}
  labels:
    {{- include "haproxy-template-ic.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  config: |
{{- .Values.controller.config | toYaml | nindent 4 }}
