apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy-template-ic.fullname" . }}
  labels:
    {{- include "haproxy-template-ic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: healthz
      protocol: TCP
      name: http
  selector:
    {{- include "haproxy-template-ic.selectorLabels" . | nindent 4 }}
