{{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.webhook.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haproxy-template-ic.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.webhook.secretName }}
  duration: {{ .Values.webhook.certManager.duration | default "8760h" }}  # 1 year
  renewBefore: {{ .Values.webhook.certManager.renewBefore | default "720h" }}  # 30 days
  dnsNames:
    - {{ include "haproxy-template-ic.fullname" . }}-webhook
    - {{ include "haproxy-template-ic.fullname" . }}-webhook.{{ .Release.Namespace }}
    - {{ include "haproxy-template-ic.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "haproxy-template-ic.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    {{- toYaml .Values.webhook.certManager.issuerRef | nindent 4 }}
  usages:
    - digital signature
    - key encipherment
    - server auth
{{- end }}
