kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: haproxy-template-ic-dev
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # HTTP traffic to HAProxy
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      # HTTPS traffic to HAProxy
      - containerPort: 30443
        hostPort: 30443
        protocol: TCP
      # HAProxy stats/health
      - containerPort: 30404
        hostPort: 30404
        protocol: TCP
# Enable required admission controllers for webhooks
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
