# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.spoe_group import SpoeGroup

class TestSpoeGroup(unittest.TestCase):
    """SpoeGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpoeGroup:
        """Test SpoeGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpoeGroup`
        """
        model = SpoeGroup()
        if include_optional:
            return SpoeGroup(
                messages = '',
                name = ''
            )
        else:
            return SpoeGroup(
                name = '',
        )
        """

    def testSpoeGroup(self):
        """Test SpoeGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
