# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.acme_certificate_status import AcmeCertificateStatus

class TestAcmeCertificateStatus(unittest.TestCase):
    """AcmeCertificateStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AcmeCertificateStatus:
        """Test AcmeCertificateStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AcmeCertificateStatus`
        """
        model = AcmeCertificateStatus()
        if include_optional:
            return AcmeCertificateStatus(
                acme_section = '',
                certificate = '',
                expiries_in = '',
                expiry_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                renewal_in = '',
                scheduled_renewal = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                state = ''
            )
        else:
            return AcmeCertificateStatus(
        )
        """

    def testAcmeCertificateStatus(self):
        """Test AcmeCertificateStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
