# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.api.group_api import GroupApi


class TestGroupApi(unittest.IsolatedAsyncioTestCase):
    """GroupApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = GroupApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_group(self) -> None:
        """Test case for create_group

        Add a new userlist group
        """
        pass

    async def test_delete_group(self) -> None:
        """Test case for delete_group

        Delete a group
        """
        pass

    async def test_get_group(self) -> None:
        """Test case for get_group

        Return one userlist group
        """
        pass

    async def test_get_groups(self) -> None:
        """Test case for get_groups

        Return an array of userlist groups
        """
        pass

    async def test_replace_group(self) -> None:
        """Test case for replace_group

        Replace a group
        """
        pass


if __name__ == '__main__':
    unittest.main()
