# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.tcp_response_rule import TcpResponseRule

class TestTcpResponseRule(unittest.TestCase):
    """TcpResponseRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TcpResponseRule:
        """Test TcpResponseRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TcpResponseRule`
        """
        model = TcpResponseRule()
        if include_optional:
            return TcpResponseRule(
                action = 'accept',
                bandwidth_limit_limit = '',
                bandwidth_limit_name = '',
                bandwidth_limit_period = '',
                cond = 'if',
                cond_test = '',
                expr = '',
                log_level = 'emerg',
                lua_action = 'k',
                lua_params = '',
                mark_value = '80728',
                metadata = None,
                nice_value = -1024,
                rst_ttl = 56,
                sc_expr = '',
                sc_id = 56,
                sc_idx = 56,
                sc_int = 56,
                spoe_engine = 'k',
                spoe_group = 'k',
                timeout = 56,
                tos_value = '80728',
                type = 'content',
                var_format = '',
                var_name = 'k',
                var_scope = 'k'
            )
        else:
            return TcpResponseRule(
                type = 'content',
        )
        """

    def testTcpResponseRule(self):
        """Test TcpResponseRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
