# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.api.configuration_api import ConfigurationApi


class TestConfigurationApi(unittest.IsolatedAsyncioTestCase):
    """ConfigurationApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ConfigurationApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_configuration_version(self) -> None:
        """Test case for get_configuration_version

        Return a configuration version
        """
        pass

    async def test_get_ha_proxy_configuration(self) -> None:
        """Test case for get_ha_proxy_configuration

        Return HAProxy configuration
        """
        pass

    async def test_post_ha_proxy_configuration(self) -> None:
        """Test case for post_ha_proxy_configuration

        Push new haproxy configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
