# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.cookie import Cookie

class TestCookie(unittest.TestCase):
    """Cookie unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Cookie:
        """Test Cookie
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Cookie`
        """
        model = Cookie()
        if include_optional:
            return Cookie(
                attr = [
                    haproxy_dataplane_v3.models.cookie_attr_inner.cookie_attr_inner(
                        value = 'k', )
                    ],
                domain = [
                    haproxy_dataplane_v3.models.cookie_domain_inner.cookie_domain_inner(
                        value = 'k', )
                    ],
                dynamic = True,
                httponly = True,
                indirect = True,
                maxidle = 56,
                maxlife = 56,
                name = 'k',
                nocache = True,
                postonly = True,
                preserve = True,
                secure = True,
                type = 'rewrite'
            )
        else:
            return Cookie(
                name = 'k',
        )
        """

    def testCookie(self):
        """Test Cookie"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
