# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.api.process_manager_api import ProcessManagerApi


class TestProcessManagerApi(unittest.IsolatedAsyncioTestCase):
    """ProcessManagerApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ProcessManagerApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_program(self) -> None:
        """Test case for create_program

        Add a program
        """
        pass

    async def test_delete_program(self) -> None:
        """Test case for delete_program

        Delete a program
        """
        pass

    async def test_get_program(self) -> None:
        """Test case for get_program

        Return a program
        """
        pass

    async def test_get_programs(self) -> None:
        """Test case for get_programs

        Return an array of programs
        """
        pass

    async def test_replace_program(self) -> None:
        """Test case for replace_program

        Replace a program
        """
        pass


if __name__ == '__main__':
    unittest.main()
