# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.peer_section_base import PeerSectionBase

class TestPeerSectionBase(unittest.TestCase):
    """PeerSectionBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PeerSectionBase:
        """Test PeerSectionBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeerSectionBase`
        """
        model = PeerSectionBase()
        if include_optional:
            return PeerSectionBase(
                default_bind = None,
                default_server = None,
                disabled = True,
                enabled = True,
                metadata = haproxy_dataplane_v3.models.metadata.metadata(),
                name = '0',
                shards = 56
            )
        else:
            return PeerSectionBase(
                name = '0',
        )
        """

    def testPeerSectionBase(self):
        """Test PeerSectionBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
