# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.monitor_fail import MonitorFail

class TestMonitorFail(unittest.TestCase):
    """MonitorFail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitorFail:
        """Test MonitorFail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitorFail`
        """
        model = MonitorFail()
        if include_optional:
            return MonitorFail(
                cond = 'if',
                cond_test = ''
            )
        else:
            return MonitorFail(
                cond = 'if',
                cond_test = '',
        )
        """

    def testMonitorFail(self):
        """Test MonitorFail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
