# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.ssl_certificate import SslCertificate

class TestSslCertificate(unittest.TestCase):
    """SslCertificate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SslCertificate:
        """Test SslCertificate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SslCertificate`
        """
        model = SslCertificate()
        if include_optional:
            return SslCertificate(
                algorithm = '',
                authority_key_id = '',
                chain_issuer = '',
                chain_subject = '',
                description = '',
                domains = '',
                file = '',
                ip_addresses = '',
                issuers = '',
                not_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                not_before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                serial = '',
                sha1_finger_print = '',
                sha256_finger_print = '',
                size = 56,
                status = '',
                storage_name = '',
                subject = '',
                subject_alternative_names = '',
                subject_key_id = ''
            )
        else:
            return SslCertificate(
        )
        """

    def testSslCertificate(self):
        """Test SslCertificate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
