# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.global_base_cpu_maps_inner import GlobalBaseCpuMapsInner

class TestGlobalBaseCpuMapsInner(unittest.TestCase):
    """GlobalBaseCpuMapsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalBaseCpuMapsInner:
        """Test GlobalBaseCpuMapsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalBaseCpuMapsInner`
        """
        model = GlobalBaseCpuMapsInner()
        if include_optional:
            return GlobalBaseCpuMapsInner(
                cpu_set = '',
                process = ''
            )
        else:
            return GlobalBaseCpuMapsInner(
                cpu_set = '',
                process = '',
        )
        """

    def testGlobalBaseCpuMapsInner(self):
        """Test GlobalBaseCpuMapsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
