# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.native_stat_stats import NativeStatStats

class TestNativeStatStats(unittest.TestCase):
    """NativeStatStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NativeStatStats:
        """Test NativeStatStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NativeStatStats`
        """
        model = NativeStatStats()
        if include_optional:
            return NativeStatStats(
                act = 56,
                addr = '',
                agent_code = 56,
                agent_desc = '',
                agent_duration = 56,
                agent_fall = 56,
                agent_health = 56,
                agent_rise = 56,
                agent_status = 'UNK',
                algo = '',
                bck = 56,
                bin = 56,
                bout = 56,
                check_code = 56,
                check_desc = '',
                check_duration = 56,
                check_fall = 56,
                check_health = 56,
                check_rise = 56,
                check_status = 'UNK',
                chkdown = 56,
                chkfail = 56,
                cli_abrt = 56,
                comp_byp = 56,
                comp_in = 56,
                comp_out = 56,
                comp_rsp = 56,
                conn_rate = 56,
                conn_rate_max = 56,
                conn_tot = 56,
                cookie = '',
                ctime = 56,
                dcon = 56,
                downtime = 56,
                dreq = 56,
                dresp = 56,
                dses = 56,
                econ = 56,
                ereq = 56,
                eresp = 56,
                hanafail = '',
                hrsp_1xx = 56,
                hrsp_2xx = 56,
                hrsp_3xx = 56,
                hrsp_4xx = 56,
                hrsp_5xx = 56,
                hrsp_other = 56,
                iid = 56,
                intercepted = 56,
                last_agt = '',
                last_chk = '',
                lastchg = 56,
                lastsess = 56,
                lbtot = 56,
                mode = 'tcp',
                pid = 56,
                qcur = 56,
                qlimit = 56,
                qmax = 56,
                qtime = 56,
                rate = 56,
                rate_lim = 56,
                rate_max = 56,
                req_rate = 56,
                req_rate_max = 56,
                req_tot = 56,
                rtime = 56,
                scur = 56,
                sid = 56,
                slim = 56,
                smax = 56,
                srv_abrt = 56,
                status = 'UP',
                stot = 56,
                throttle = 56,
                tracked = '',
                ttime = 56,
                weight = 56,
                wredis = 56,
                wretr = 56
            )
        else:
            return NativeStatStats(
        )
        """

    def testNativeStatStats(self):
        """Test NativeStatStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
