# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.runtime_add_server import RuntimeAddServer

class TestRuntimeAddServer(unittest.TestCase):
    """RuntimeAddServer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuntimeAddServer:
        """Test RuntimeAddServer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuntimeAddServer`
        """
        model = RuntimeAddServer()
        if include_optional:
            return RuntimeAddServer(
                address = 'k',
                agent_addr = 'k',
                agent_check = 'enabled',
                agent_inter = 0,
                agent_port = 1,
                agent_send = '',
                allow_0rtt = True,
                alpn = 'k',
                backup = 'enabled',
                check = 'enabled',
                check_send_proxy = 'enabled',
                check_sni = 'k',
                check_ssl = 'enabled',
                check_alpn = 'k',
                check_proto = 'k',
                check_via_socks4 = 'enabled',
                ciphers = '',
                ciphersuites = '',
                crl_file = '',
                downinter = 0,
                error_limit = 56,
                fall = 56,
                fastinter = 0,
                force_sslv3 = 'enabled',
                force_tlsv10 = 'enabled',
                force_tlsv11 = 'enabled',
                force_tlsv12 = 'enabled',
                force_tlsv13 = 'enabled',
                health_check_address = 'k',
                health_check_port = 1,
                id = '',
                inter = 0,
                maintenance = 'enabled',
                maxconn = 56,
                maxqueue = 56,
                minconn = 56,
                name = '',
                no_sslv3 = 'enabled',
                no_tlsv10 = 'enabled',
                no_tlsv11 = 'enabled',
                no_tlsv12 = 'enabled',
                no_tlsv13 = 'enabled',
                npn = '',
                observe = 'layer4',
                on_error = 'fastinter',
                on_marked_down = 'shutdown-sessions',
                on_marked_up = 'shutdown-backup-sessions',
                pool_low_conn = 56,
                pool_max_conn = 56,
                pool_purge_delay = 0,
                port = 1,
                proto = 'k',
                proxy_v2_options = [
                    'authority'
                    ],
                rise = 56,
                send_proxy = 'enabled',
                send_proxy_v2 = 'enabled',
                send_proxy_v2_ssl = 'enabled',
                send_proxy_v2_ssl_cn = 'enabled',
                slowstart = 0,
                sni = 'k',
                source = '',
                ssl = 'enabled',
                ssl_cafile = 'k',
                ssl_certificate = 'k',
                ssl_max_ver = 'SSLv3',
                ssl_min_ver = 'SSLv3',
                ssl_reuse = 'enabled',
                tfo = 'enabled',
                tls_tickets = 'enabled',
                track = '',
                verify = 'none',
                verifyhost = '',
                weight = 56,
                ws = 'auto'
            )
        else:
            return RuntimeAddServer(
        )
        """

    def testRuntimeAddServer(self):
        """Test RuntimeAddServer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
