# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.api.bind_api import BindApi


class TestBindApi(unittest.IsolatedAsyncioTestCase):
    """BindApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = BindApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_bind_frontend(self) -> None:
        """Test case for create_bind_frontend

        Add a new bind
        """
        pass

    async def test_create_bind_log_forward(self) -> None:
        """Test case for create_bind_log_forward

        Add a new bind
        """
        pass

    async def test_create_bind_peer(self) -> None:
        """Test case for create_bind_peer

        Add a new bind
        """
        pass

    async def test_delete_bind_frontend(self) -> None:
        """Test case for delete_bind_frontend

        Delete a bind
        """
        pass

    async def test_delete_bind_log_forward(self) -> None:
        """Test case for delete_bind_log_forward

        Delete a bind
        """
        pass

    async def test_delete_bind_peer(self) -> None:
        """Test case for delete_bind_peer

        Delete a bind
        """
        pass

    async def test_get_all_bind_frontend(self) -> None:
        """Test case for get_all_bind_frontend

        Return an array of binds
        """
        pass

    async def test_get_all_bind_log_forward(self) -> None:
        """Test case for get_all_bind_log_forward

        Return an array of binds
        """
        pass

    async def test_get_all_bind_peer(self) -> None:
        """Test case for get_all_bind_peer

        Return an array of binds
        """
        pass

    async def test_get_bind_frontend(self) -> None:
        """Test case for get_bind_frontend

        Return one bind
        """
        pass

    async def test_get_bind_log_forward(self) -> None:
        """Test case for get_bind_log_forward

        Return one bind
        """
        pass

    async def test_get_bind_peer(self) -> None:
        """Test case for get_bind_peer

        Return one bind
        """
        pass

    async def test_replace_bind_frontend(self) -> None:
        """Test case for replace_bind_frontend

        Replace a bind
        """
        pass

    async def test_replace_bind_log_forward(self) -> None:
        """Test case for replace_bind_log_forward

        Replace a bind
        """
        pass

    async def test_replace_bind_peer(self) -> None:
        """Test case for replace_bind_peer

        Replace a bind
        """
        pass


if __name__ == '__main__':
    unittest.main()
