# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.ssl_options_engines_inner import SslOptionsEnginesInner

class TestSslOptionsEnginesInner(unittest.TestCase):
    """SslOptionsEnginesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SslOptionsEnginesInner:
        """Test SslOptionsEnginesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SslOptionsEnginesInner`
        """
        model = SslOptionsEnginesInner()
        if include_optional:
            return SslOptionsEnginesInner(
                algorithms = '',
                name = ''
            )
        else:
            return SslOptionsEnginesInner(
                name = '',
        )
        """

    def testSslOptionsEnginesInner(self):
        """Test SslOptionsEnginesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
