# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.tune_zlib_options import TuneZlibOptions

class TestTuneZlibOptions(unittest.TestCase):
    """TuneZlibOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TuneZlibOptions:
        """Test TuneZlibOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TuneZlibOptions`
        """
        model = TuneZlibOptions()
        if include_optional:
            return TuneZlibOptions(
                memlevel = 1,
                windowsize = 8
            )
        else:
            return TuneZlibOptions(
        )
        """

    def testTuneZlibOptions(self):
        """Test TuneZlibOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
