# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.ssl_ocsp_update import SslOcspUpdate

class TestSslOcspUpdate(unittest.TestCase):
    """SslOcspUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SslOcspUpdate:
        """Test SslOcspUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SslOcspUpdate`
        """
        model = SslOcspUpdate()
        if include_optional:
            return SslOcspUpdate(
                cert_id = '',
                failures = 56,
                last_update = '',
                last_update_status = 56,
                last_update_status_str = '',
                next_update = '',
                path = '',
                successes = 56
            )
        else:
            return SslOcspUpdate(
        )
        """

    def testSslOcspUpdate(self):
        """Test SslOcspUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
