# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.info_system import InfoSystem

class TestInfoSystem(unittest.TestCase):
    """InfoSystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InfoSystem:
        """Test InfoSystem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InfoSystem`
        """
        model = InfoSystem()
        if include_optional:
            return InfoSystem(
                cpu_info = haproxy_dataplane_v3.models.info_system_cpu_info.info_system_cpu_info(
                    model = '', 
                    num_cpus = 56, ),
                hostname = '',
                mem_info = haproxy_dataplane_v3.models.info_system_mem_info.info_system_mem_info(
                    dataplaneapi_memory = 56, 
                    free_memory = 56, 
                    total_memory = 56, ),
                os_string = '',
                time = 56,
                uptime = 56
            )
        else:
            return InfoSystem(
        )
        """

    def testInfoSystem(self):
        """Test InfoSystem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
