# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.ring_base import RingBase

class TestRingBase(unittest.TestCase):
    """RingBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RingBase:
        """Test RingBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RingBase`
        """
        model = RingBase()
        if include_optional:
            return RingBase(
                description = '',
                format = 'iso',
                maxlen = 56,
                metadata = haproxy_dataplane_v3.models.metadata.metadata(),
                name = '0',
                size = 0,
                timeout_connect = 0,
                timeout_server = 0
            )
        else:
            return RingBase(
                name = '0',
        )
        """

    def testRingBase(self):
        """Test RingBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
