# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.tune_ssl_options import TuneSslOptions

class TestTuneSslOptions(unittest.TestCase):
    """TuneSslOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TuneSslOptions:
        """Test TuneSslOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TuneSslOptions`
        """
        model = TuneSslOptions()
        if include_optional:
            return TuneSslOptions(
                cachesize = 56,
                capture_buffer_size = 56,
                ctx_cache_size = 56,
                default_dh_param = 56,
                force_private_cache = True,
                keylog = 'enabled',
                lifetime = 0,
                maxrecord = 56,
                ocsp_update_max_delay = 56,
                ocsp_update_min_delay = 56
            )
        else:
            return TuneSslOptions(
        )
        """

    def testTuneSslOptions(self):
        """Test TuneSslOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
