# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.api.acl_runtime_api import ACLRuntimeApi


class TestACLRuntimeApi(unittest.IsolatedAsyncioTestCase):
    """ACLRuntimeApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ACLRuntimeApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_add_payload_runtime_acl(self) -> None:
        """Test case for add_payload_runtime_acl

        Add a new ACL payload
        """
        pass

    async def test_services_haproxy_runtime_acls_get(self) -> None:
        """Test case for services_haproxy_runtime_acls_get

        Return an array of all ACL files
        """
        pass

    async def test_services_haproxy_runtime_acls_id_get(self) -> None:
        """Test case for services_haproxy_runtime_acls_id_get

        Return an ACL file
        """
        pass

    async def test_services_haproxy_runtime_acls_parent_name_entries_get(self) -> None:
        """Test case for services_haproxy_runtime_acls_parent_name_entries_get

        Return an ACL entries
        """
        pass

    async def test_services_haproxy_runtime_acls_parent_name_entries_id_delete(self) -> None:
        """Test case for services_haproxy_runtime_acls_parent_name_entries_id_delete

        Delete an ACL entry
        """
        pass

    async def test_services_haproxy_runtime_acls_parent_name_entries_id_get(self) -> None:
        """Test case for services_haproxy_runtime_acls_parent_name_entries_id_get

        Return an ACL entry
        """
        pass

    async def test_services_haproxy_runtime_acls_parent_name_entries_post(self) -> None:
        """Test case for services_haproxy_runtime_acls_parent_name_entries_post

        Add entry to an ACL file
        """
        pass


if __name__ == '__main__':
    unittest.main()
