# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.tune_quic_options import TuneQuicOptions

class TestTuneQuicOptions(unittest.TestCase):
    """TuneQuicOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TuneQuicOptions:
        """Test TuneQuicOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TuneQuicOptions`
        """
        model = TuneQuicOptions()
        if include_optional:
            return TuneQuicOptions(
                frontend_conn_tx_buffers_limit = 56,
                frontend_max_idle_timeout = 0,
                frontend_max_streams_bidi = 56,
                frontend_max_tx_memory = 56,
                max_frame_loss = 56,
                reorder_ratio = 0,
                retry_threshold = 56,
                socket_owner = 'listener',
                zero_copy_fwd_send = 'enabled'
            )
        else:
            return TuneQuicOptions(
        )
        """

    def testTuneQuicOptions(self):
        """Test TuneQuicOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
