# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.consul import Consul

class TestConsul(unittest.TestCase):
    """Consul unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Consul:
        """Test Consul
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Consul`
        """
        model = Consul()
        if include_optional:
            return Consul(
                address = 'k',
                defaults = '',
                description = '',
                enabled = True,
                health_check_policy = 'none',
                health_check_policy_min = 56,
                id = 'k',
                mode = 'http',
                name = '',
                namespace = '',
                port = 1,
                retry_timeout = 1,
                server_slots_base = 56,
                server_slots_growth_increment = 56,
                server_slots_growth_type = 'exponential',
                service_allowlist = [
                    'k'
                    ],
                service_denylist = [
                    'k'
                    ],
                service_name_regexp = '',
                token = 'k'
            )
        else:
            return Consul(
                address = 'k',
                enabled = True,
                port = 1,
                retry_timeout = 1,
        )
        """

    def testConsul(self):
        """Test Consul"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
