# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.ssl_ocsp_response import SslOcspResponse

class TestSslOcspResponse(unittest.TestCase):
    """SslOcspResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SslOcspResponse:
        """Test SslOcspResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SslOcspResponse`
        """
        model = SslOcspResponse()
        if include_optional:
            return SslOcspResponse(
                base64_response = '',
                ocsp_response_status = '',
                produced_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                responder_id = [
                    ''
                    ],
                response_type = '',
                responses = haproxy_dataplane_v3.models.ssl_ocsp_response_responses.ssl_ocsp_response_responses(
                    cert_status = '', 
                    certificate_id = None, 
                    next_update = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    revocation_reason = '', 
                    this_update = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                version = ''
            )
        else:
            return SslOcspResponse(
        )
        """

    def testSslOcspResponse(self):
        """Test SslOcspResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
