# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.nameserver import Nameserver

class TestNameserver(unittest.TestCase):
    """Nameserver unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Nameserver:
        """Test Nameserver
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Nameserver`
        """
        model = Nameserver()
        if include_optional:
            return Nameserver(
                address = 'k',
                metadata = None,
                name = '0',
                port = 1
            )
        else:
            return Nameserver(
                address = 'k',
                name = '0',
        )
        """

    def testNameserver(self):
        """Test Nameserver"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
