# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.api.health_api import HealthApi


class TestHealthApi(unittest.IsolatedAsyncioTestCase):
    """HealthApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = HealthApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_health(self) -> None:
        """Test case for get_health

        Return managed services health
        """
        pass


if __name__ == '__main__':
    unittest.main()
