# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.mailers_section_base import MailersSectionBase

class TestMailersSectionBase(unittest.TestCase):
    """MailersSectionBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MailersSectionBase:
        """Test MailersSectionBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailersSectionBase`
        """
        model = MailersSectionBase()
        if include_optional:
            return MailersSectionBase(
                metadata = haproxy_dataplane_v3.models.metadata.metadata(),
                name = 'z',
                timeout = 0
            )
        else:
            return MailersSectionBase(
                name = 'z',
        )
        """

    def testMailersSectionBase(self):
        """Test MailersSectionBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
