# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.api.ssl_runtime_api import SSLRuntimeApi


class TestSSLRuntimeApi(unittest.IsolatedAsyncioTestCase):
    """SSLRuntimeApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SSLRuntimeApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_add_ca_entry(self) -> None:
        """Test case for add_ca_entry

        Add a certificate to a CA file
        """
        pass

    async def test_add_crt_list_entry(self) -> None:
        """Test case for add_crt_list_entry

        Add an entry into a crt-list
        """
        pass

    async def test_create_ca_file(self) -> None:
        """Test case for create_ca_file

        Creates a new SSL CA file
        """
        pass

    async def test_create_cert(self) -> None:
        """Test case for create_cert

        Create a new SSL certificate file
        """
        pass

    async def test_create_crl(self) -> None:
        """Test case for create_crl

        Create a new CRL file
        """
        pass

    async def test_delete_ca_file(self) -> None:
        """Test case for delete_ca_file

        Deletes a CA file
        """
        pass

    async def test_delete_cert(self) -> None:
        """Test case for delete_cert

        Delete a certificate
        """
        pass

    async def test_delete_crl(self) -> None:
        """Test case for delete_crl

        Delete a CRL file
        """
        pass

    async def test_delete_crt_list_entry(self) -> None:
        """Test case for delete_crt_list_entry

        Delete an entry from a crt-list
        """
        pass

    async def test_get_all_ca_files(self) -> None:
        """Test case for get_all_ca_files

        Return an array of all SSL CA files
        """
        pass

    async def test_get_all_certs(self) -> None:
        """Test case for get_all_certs

        Return a list of SSL certificate files
        """
        pass

    async def test_get_all_crl(self) -> None:
        """Test case for get_all_crl

        Return an array of all the CRL files
        """
        pass

    async def test_get_all_crt_list_entries(self) -> None:
        """Test case for get_all_crt_list_entries

        Get all the entries inside a crt-list
        """
        pass

    async def test_get_all_crt_lists(self) -> None:
        """Test case for get_all_crt_lists

        Get the list of all crt-list files
        """
        pass

    async def test_get_ca_entry(self) -> None:
        """Test case for get_ca_entry

        Return an SSL CA file cert entry
        """
        pass

    async def test_get_ca_file(self) -> None:
        """Test case for get_ca_file

        Return an SSL CA file
        """
        pass

    async def test_get_cert(self) -> None:
        """Test case for get_cert

        Return one structured certificate
        """
        pass

    async def test_get_crl(self) -> None:
        """Test case for get_crl

        Get the contents of a CRL file
        """
        pass

    async def test_replace_cert(self) -> None:
        """Test case for replace_cert

        Replace the contents of a certificate
        """
        pass

    async def test_replace_crl(self) -> None:
        """Test case for replace_crl

        Replace the contents of a CRL file
        """
        pass

    async def test_set_ca_file(self) -> None:
        """Test case for set_ca_file

        Update the contents of a CA file
        """
        pass


if __name__ == '__main__':
    unittest.main()
