# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.native_stat import NativeStat

class TestNativeStat(unittest.TestCase):
    """NativeStat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NativeStat:
        """Test NativeStat
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NativeStat`
        """
        model = NativeStat()
        if include_optional:
            return NativeStat(
                backend_name = '',
                name = '',
                stats = {bin=4326578, bout=889901290, comp_byp=0, comp_in=0, comp_out=0, comp_rsp=0, conn_rate=12, conn_rate_max=456, conn_tot=45682, dcon=0, dreq=4, dresp=1, dses=0, ereq=54, hrsp_1xx=0, hrsp_2xx=165, hrsp_3xx=12, hrsp_4xx=50, hrsp_5xx=4, hrsp_other=0, iid=0, intercepted=346, last_chk=L4OK in 0ms, mode=http, pid=3204, rate=64, rate_lim=20000, rate_max=4000, req_rate=49, req_rate_max=3965, req_total=1254786, scur=129, slim=2000, smax=2000, status=UP, stot=12902},
                type = 'backend'
            )
        else:
            return NativeStat(
        )
        """

    def testNativeStat(self):
        """Test NativeStat"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
