# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.ssl_ocsp_response_responses import SslOcspResponseResponses

class TestSslOcspResponseResponses(unittest.TestCase):
    """SslOcspResponseResponses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SslOcspResponseResponses:
        """Test SslOcspResponseResponses
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SslOcspResponseResponses`
        """
        model = SslOcspResponseResponses()
        if include_optional:
            return SslOcspResponseResponses(
                cert_status = '',
                certificate_id = haproxy_dataplane_v3.models.ssl_certificate_id_certificate_id.ssl_certificate_id_certificate_id(
                    hash_algorithm = '', 
                    issuer_key_hash = '', 
                    issuer_name_hash = '', 
                    serial_number = '', ),
                next_update = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                revocation_reason = '',
                this_update = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return SslOcspResponseResponses(
        )
        """

    def testSslOcspResponseResponses(self):
        """Test SslOcspResponseResponses"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
