# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.global_base_harden import GlobalBaseHarden

class TestGlobalBaseHarden(unittest.TestCase):
    """GlobalBaseHarden unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalBaseHarden:
        """Test GlobalBaseHarden
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GlobalBaseHarden`
        """
        model = GlobalBaseHarden()
        if include_optional:
            return GlobalBaseHarden(
                reject_privileged_ports = haproxy_dataplane_v3.models.global_base_harden_reject_privileged_ports.global_base_harden_reject_privileged_ports(
                    quic = 'enabled', 
                    tcp = 'enabled', )
            )
        else:
            return GlobalBaseHarden(
        )
        """

    def testGlobalBaseHarden(self):
        """Test GlobalBaseHarden"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
