# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.api.discovery_api import DiscoveryApi


class TestDiscoveryApi(unittest.IsolatedAsyncioTestCase):
    """DiscoveryApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DiscoveryApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_api_endpoints(self) -> None:
        """Test case for get_api_endpoints

        Return list of root endpoints
        """
        pass

    async def test_get_configuration_endpoints(self) -> None:
        """Test case for get_configuration_endpoints

        Return list of HAProxy advanced configuration endpoints
        """
        pass

    async def test_get_haproxy_endpoints(self) -> None:
        """Test case for get_haproxy_endpoints

        Return list of HAProxy related endpoints
        """
        pass

    async def test_get_runtime_endpoints(self) -> None:
        """Test case for get_runtime_endpoints

        Return list of HAProxy advanced runtime endpoints
        """
        pass

    async def test_get_services_endpoints(self) -> None:
        """Test case for get_services_endpoints

        Return list of service endpoints
        """
        pass

    async def test_get_spoe_endpoints(self) -> None:
        """Test case for get_spoe_endpoints

        Return list of HAProxy SPOE endpoints
        """
        pass

    async def test_get_stats_endpoints(self) -> None:
        """Test case for get_stats_endpoints

        Return list of HAProxy stats endpoints
        """
        pass

    async def test_get_storage_endpoints(self) -> None:
        """Test case for get_storage_endpoints

        Return list of HAProxy storage endpoints
        """
        pass


if __name__ == '__main__':
    unittest.main()
