# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.defaults_base import DefaultsBase

class TestDefaultsBase(unittest.TestCase):
    """DefaultsBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultsBase:
        """Test DefaultsBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultsBase`
        """
        model = DefaultsBase()
        if include_optional:
            return DefaultsBase(
                abortonclose = 'enabled',
                accept_invalid_http_request = 'enabled',
                accept_invalid_http_response = 'enabled',
                accept_unsafe_violations_in_http_request = 'enabled',
                accept_unsafe_violations_in_http_response = 'enabled',
                adv_check = 'httpchk',
                allbackups = 'enabled',
                backlog = 56,
                balance = haproxy_dataplane_v3.models.balance.balance(
                    algorithm = 'first', 
                    hash_expression = '', 
                    hdr_name = '', 
                    hdr_use_domain_only = True, 
                    random_draws = 56, 
                    rdp_cookie_name = 'k', 
                    uri_depth = 56, 
                    uri_len = 56, 
                    uri_path_only = True, 
                    uri_whole = True, 
                    url_param = 'k', 
                    url_param_check_post = 56, 
                    url_param_max_wait = 56, ),
                check_timeout = 56,
                checkcache = 'enabled',
                clflog = True,
                client_fin_timeout = 0,
                client_timeout = 0,
                clitcpka = 'enabled',
                clitcpka_cnt = 56,
                clitcpka_idle = 56,
                clitcpka_intvl = 56,
                compression = haproxy_dataplane_v3.models.compression.compression(
                    algo_req = 'identity', 
                    algorithms = [
                        'identity'
                        ], 
                    algos_res = [
                        'identity'
                        ], 
                    direction = 'request', 
                    minsize_req = 56, 
                    minsize_res = 56, 
                    offload = True, 
                    types = [
                        ''
                        ], 
                    types_req = [
                        ''
                        ], 
                    types_res = [
                        ''
                        ], ),
                connect_timeout = 0,
                contstats = 'enabled',
                cookie = haproxy_dataplane_v3.models.cookie.cookie(
                    attr = [
                        haproxy_dataplane_v3.models.cookie_attr_inner.cookie_attr_inner(
                            value = 'k', )
                        ], 
                    domain = [
                        haproxy_dataplane_v3.models.cookie_domain_inner.cookie_domain_inner(
                            value = 'k', )
                        ], 
                    dynamic = True, 
                    httponly = True, 
                    indirect = True, 
                    maxidle = 56, 
                    maxlife = 56, 
                    name = 'k', 
                    nocache = True, 
                    postonly = True, 
                    preserve = True, 
                    secure = True, 
                    type = 'rewrite', ),
                default_backend = '0',
                default_server = None,
                disable_h2_upgrade = 'enabled',
                disabled = True,
                dontlog_normal = 'enabled',
                dontlognull = 'enabled',
                dynamic_cookie_key = 'k',
                email_alert = haproxy_dataplane_v3.models.email_alert.Email Alert(
                    from = 'k@?x!u\'K}qz^sEC)lJ*=-jQ+\'6`%cClu,k\'!\'su[.', 
                    level = 'emerg', 
                    mailers = '', 
                    metadata = haproxy_dataplane_v3.models.metadata.metadata(), 
                    myhostname = '', 
                    to = 'k@?x!u\'K}qz^sEC)lJ*=-jQ+\'6`%cClu,k\'!\'su[.', ),
                enabled = True,
                error_files = [
                    haproxy_dataplane_v3.models.errorfile.errorfile(
                        code = 56, 
                        file = '', )
                    ],
                error_log_format = '',
                errorfiles_from_http_errors = [
                    haproxy_dataplane_v3.models.errorfiles.errorfiles(
                        codes = [
                            56
                            ], 
                        metadata = haproxy_dataplane_v3.models.metadata.metadata(), 
                        name = '', )
                    ],
                errorloc302 = haproxy_dataplane_v3.models.errorloc.errorloc(
                    code = 56, 
                    metadata = haproxy_dataplane_v3.models.metadata.metadata(), 
                    url = '', ),
                errorloc303 = haproxy_dataplane_v3.models.errorloc.errorloc(
                    code = 56, 
                    metadata = haproxy_dataplane_v3.models.metadata.metadata(), 
                    url = '', ),
                external_check = 'enabled',
                external_check_command = 'k',
                external_check_path = 'k',
                forwardfor = haproxy_dataplane_v3.models.forwardfor.forwardfor(
                    enabled = 'enabled', 
                    except = 'k', 
                    header = 'k', 
                    ifnone = True, ),
                var_from = '0',
                fullconn = 56,
                h1_case_adjust_bogus_client = 'enabled',
                h1_case_adjust_bogus_server = 'enabled',
                hash_balance_factor = 56,
                hash_preserve_affinity = 'always',
                hash_type = haproxy_dataplane_v3.models.hash_type.hash_type(
                    function = 'sdbm', 
                    method = 'map-based', 
                    modifier = 'avalanche', ),
                http_buffer_request = 'enabled',
                http_drop_request_trailers = 'enabled',
                http_drop_response_trailers = 'enabled',
                http_use_htx = 'enabled',
                http_connection_mode = 'httpclose',
                http_ignore_probes = 'enabled',
                http_keep_alive_timeout = 0,
                http_no_delay = 'enabled',
                http_pretend_keepalive = 'enabled',
                http_request_timeout = 0,
                http_restrict_req_hdr_names = 'preserve',
                http_reuse = 'aggressive',
                http_send_name_header = '',
                http_use_proxy_header = 'enabled',
                httpchk_params = haproxy_dataplane_v3.models.httpchk_params.httpchk_params(
                    host = '', 
                    method = 'HEAD', 
                    uri = 'k%?x!u\'K}qz^sEC)lJ*=-j', 
                    version = '', ),
                httplog = True,
                httpslog = 'enabled',
                idle_close_on_response = 'enabled',
                independent_streams = 'enabled',
                load_server_state_from_file = 'global',
                log_format = '',
                log_format_sd = '',
                log_health_checks = 'enabled',
                log_separate_errors = 'enabled',
                log_steps = [
                    'accept'
                    ],
                log_tag = 'k',
                logasap = 'enabled',
                max_keep_alive_queue = 56,
                maxconn = 56,
                metadata = haproxy_dataplane_v3.models.metadata.metadata(),
                mode = 'tcp',
                monitor_uri = '',
                mysql_check_params = haproxy_dataplane_v3.models.mysql_check_params.mysql_check_params(
                    client_version = 'pre-41', 
                    username = '', ),
                name = '0',
                nolinger = 'enabled',
                originalto = haproxy_dataplane_v3.models.originalto.originalto(
                    enabled = 'enabled', 
                    except = 'k', 
                    header = 'k', ),
                persist = 'enabled',
                persist_rule = haproxy_dataplane_v3.models.persist_rule.persist_rule(
                    rdp_cookie_name = 'k', 
                    type = 'rdp-cookie', ),
                pgsql_check_params = haproxy_dataplane_v3.models.pgsql_check_params.pgsql_check_params(
                    username = '', ),
                prefer_last_server = 'enabled',
                queue_timeout = 0,
                redispatch = haproxy_dataplane_v3.models.redispatch.redispatch(
                    enabled = 'enabled', 
                    interval = 56, ),
                retries = 56,
                retry_on = '',
                server_fin_timeout = 0,
                server_timeout = 0,
                smtpchk_params = haproxy_dataplane_v3.models.smtpchk_params.smtpchk_params(
                    domain = '', 
                    hello = '', ),
                socket_stats = 'enabled',
                source = haproxy_dataplane_v3.models.source.source(
                    address = '', 
                    address_second = '', 
                    hdr = '', 
                    interface = '', 
                    occ = '', 
                    port = 1, 
                    port_second = 1, 
                    usesrc = 'address', ),
                splice_auto = 'enabled',
                splice_request = 'enabled',
                splice_response = 'enabled',
                srvtcpka = 'enabled',
                srvtcpka_cnt = 56,
                srvtcpka_idle = 56,
                srvtcpka_intvl = 56,
                stats_options = haproxy_dataplane_v3.models.stats_options.stats_options(
                    stats_admin = True, 
                    stats_admin_cond = 'if', 
                    stats_admin_cond_test = '', 
                    stats_auths = [
                        haproxy_dataplane_v3.models.stats_auth.stats_auth(
                            passwd = '', 
                            user = '', )
                        ], 
                    stats_enable = True, 
                    stats_hide_version = True, 
                    stats_http_requests = [
                        haproxy_dataplane_v3.models.stats_http_request.stats_http_request(
                            cond = '', 
                            cond_test = '', 
                            realm = '', 
                            type = 'allow', )
                        ], 
                    stats_maxconn = 1, 
                    stats_realm = True, 
                    stats_realm_realm = '', 
                    stats_refresh_delay = 0, 
                    stats_show_desc = '', 
                    stats_show_legends = True, 
                    stats_show_modules = True, 
                    stats_show_node_name = 'k', 
                    stats_uri_prefix = 'k', ),
                tarpit_timeout = 0,
                tcp_smart_accept = 'enabled',
                tcp_smart_connect = 'enabled',
                tcpka = 'enabled',
                tcplog = True,
                transparent = 'enabled',
                tunnel_timeout = 0,
                unique_id_format = '',
                unique_id_header = ''
            )
        else:
            return DefaultsBase(
        )
        """

    def testDefaultsBase(self):
        """Test DefaultsBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
