# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.aws_region import AwsRegion

class TestAwsRegion(unittest.TestCase):
    """AwsRegion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AwsRegion:
        """Test AwsRegion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AwsRegion`
        """
        model = AwsRegion()
        if include_optional:
            return AwsRegion(
                access_key_id = '',
                allowlist = [
                    haproxy_dataplane_v3.models.aws_filters.awsFilters(
                        key = '', 
                        value = '', )
                    ],
                denylist = [
                    haproxy_dataplane_v3.models.aws_filters.awsFilters(
                        key = '', 
                        value = '', )
                    ],
                description = '',
                enabled = True,
                id = 'k',
                ipv4_address = 'private',
                name = '',
                region = '',
                retry_timeout = 1,
                secret_access_key = '',
                server_slots_base = 56,
                server_slots_growth_increment = 56,
                server_slots_growth_type = 'exponential'
            )
        else:
            return AwsRegion(
                enabled = True,
                ipv4_address = 'private',
                name = '',
                region = '',
                retry_timeout = 1,
        )
        """

    def testAwsRegion(self):
        """Test AwsRegion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
