# coding: utf-8

"""
    HAProxy Data Plane API

    API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 

    The version of the OpenAPI document: 3.2
    Contact: support@haproxy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from haproxy_dataplane_v3.models.tune_buffer_options import TuneBufferOptions

class TestTuneBufferOptions(unittest.TestCase):
    """TuneBufferOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TuneBufferOptions:
        """Test TuneBufferOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TuneBufferOptions`
        """
        model = TuneBufferOptions()
        if include_optional:
            return TuneBufferOptions(
                buffers_limit = 56,
                buffers_reserve = 2,
                bufsize = 56,
                bufsize_small = 1,
                pipesize = 56,
                rcvbuf_backend = 56,
                rcvbuf_client = 56,
                rcvbuf_frontend = 56,
                rcvbuf_server = 56,
                recv_enough = 56,
                sndbuf_backend = 56,
                sndbuf_client = 56,
                sndbuf_frontend = 56,
                sndbuf_server = 56
            )
        else:
            return TuneBufferOptions(
        )
        """

    def testTuneBufferOptions(self):
        """Test TuneBufferOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
